### ISSUE TITLE
Discussion about Prisma 2 integration

### ISSUE THREAD

**Issue by MichalLytek** [MichalLytek/typegraphql-prisma#1]
> # This issue was transferred [from the main repo](https://github.com/MichalLytek/type-graphql). Be aware that some links in this discussion might be outdated.

I am thrilled to present the first preview of the upcoming **TypeGraphQL** & **Prisma Framework** integration 🎉 

![integration logo](https://raw.githubusercontent.com/MichalLytek/typegraphql-prisma/main/img/integration.png)

You can install it right now - it's distributed as a package `typegraphql-prisma` on NPM:
https://www.npmjs.com/package/typegraphql-prisma

All the docs (in readme), examples and the source code of the integration are located on the `prisma` branch of this repo (in the future it will be moved into a `master` branch when I finish converting the project to a monorepo):
https://github.com/MichalLytek/type-graphql/tree/prisma

Currently released version `0.x` is just a preview - it lacks some customization option, like picking/omitting fields of object types to expose in the schema, as well as picking CRUD methods and exposed args. However, the base functionality is working well, so I strongly encourage you to give it a try and play with it. 

Any feedback about the developers experience, bug reports or ideas about new features or enhancements are very welcome. However, during the preview I would ask to use the dedicated Gitter room if you have any questions:
https://gitter.im/type-graphql/prisma2
If you have a bug report, feel free to __add comments only in this issue__, not to create a new issues, as I don't want to pollute the repo for now 😉

And in the near feature - when Prisma SDK will be ready - the `typegraphql-prisma` integration will also allow to use a code-first approach to build a `schema.prisma` and GraphQL schema at once, using classes with decorators as a single source of truth. Stay tuned! :muscle:

**Comment by MichalLytek** [comment]
`@everybody` 👋 

I've decided to move to a separate repo for the `typegraphql-prisma` package:
- starting from now, please use this repo issue to report some bugs instead of this thread
- this thread can act for now as a place for discussion, let's see how it gonna work 🤔 
- go ahead and add a star for this repo! 🌟 

Also, all the release info will be using GitHub release board.
You can go check there to see [what's changed in the latest `v0.8.0` release](https://github.com/MichalLytek/typegraphql-prisma/releases/tag/v0.8.0) 🚀

**Comment by jsefiani** [comment]
Starred!
@MichalLytek Share the model is this thread?

**Comment by jsefiani** [comment]
@MichalLytek Here's my Prisma schema.
`
generator client {
  provider = "prisma-client-js"
}

generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "./generated/type-graphql"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator dbml {
  provider = "prisma-dbml-generator"
}

model Catalog {
  id                       Int          @id @default(autoincrement())
  productId                String?
  productName              String?
  sku                      String?
  primaryCategory          String?
  secondaryCategory        String?
  productUrl               String?
  imageUrl                 String?
  buyUrl                   String?
  shortDescription         String?
  longDescription          String?
  discount                 String?
  discountType             String?
  salePrice                String?
  retailPrice              String?
  beginDate                String?
  endDate                  String?
  brand                    String?
  shippingCost             String?
  queries                  String?
  manufacturerPartNumber   String?
  manufacturerName         String?
  shippingInformation      String?
  availability             String?
  universalProductCode     String?
  classId                  String?
  currency                 String?
  m1                       String?
  pixel                    String?
  miscellaneous            String?
  productType              String?
  size                     String?
  material                 String?
  color                    String?
  gender                   String?
  style                    String?
  age                      String?
  introPurchaseAPRDuration String?
  ongoingPurchaseAPR       String?
  status                   curatestatus @default(unreviewed)
  createdAt                DateTime     @default(now())
}

enum curatestatus {
  accepted
  declined
  pending
  unreviewed
}

`

**Comment by MichalLytek** [comment]
> @MichalLytek Share the model is this thread?

@jsefiani "starting from now, please use this repo issues to report some bugs instead of this thread"

**Comment by codejamninja** [comment]
@MichalLytek nice

**Comment by MichalLytek** [comment]
I've just released the `v0.8.1` release 🚀 
Changelog available in github release notes: https://github.com/MichalLytek/typegraphql-prisma/releases/tag/v0.8.1

I won't publish notifications here anymore, so if you want to keep informed, please enable watching this repository releases:

![image](https://user-images.githubusercontent.com/10618781/95769113-aa430700-0cb7-11eb-9011-4bf6e14d1d33.png)

**Comment by Saggitarie** [comment]
Hi @MichalLytek, 
I was wondering if you guys have any Discord or Slack Channel to ask about this package.
I asked a question on Prisma Slack Channel, but I think nobody there is familiar with this technology. (Since it's fairly new)

I was wondering how stable this package is because I had a bad experience with Nexus Framework. (They did a good job, but they stopped to support recently so)

**Comment by konuch** [comment]
> Hi @MichalLytek,
> I was wondering if you guys have any Discord or Slack Channel to ask about this package.
> I asked a question on Prisma Slack Channel, but I think nobody there is familiar with this technology. (Since it's fairly new)
> 
> I was wondering how stable this package is because I had a bad experience with Nexus Framework. (They did a good job, but they stopped to support recently so)

You can join this gitter channel. There is a prisma2 room.
https://gitter.im/type-graphql?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by DakotaLarson** [comment]
Hi @MichalLytek I am running into some issues using Prisma v2.20.1 and typegraphql-prisma v0.13.1, which I currently believe is related to: https://github.com/prisma/prisma/issues/6329. Do you know where progress is at for supporting Prisma v2.21.2? I believe this version of Prisma will resolve some of the issues I am having currently.

Thanks!

**Comment by DakotaLarson** [comment]
I guess as mentioned in the docs, this can be run `SKIP_PRISMA_VERSION_CHECK=true npx prisma generate` and works for me until an update can be pushed.

**Comment by MichalLytek** [comment]
@DakotaLarson `v0.14.0` has been released, which contains support for `Prisma v2.21.2`

**Comment by nihiluis** [comment]
@MichalLytek close this? It's confusing, I almost thought typergaphql-prisma was not compatible with Prisma 2.
