### ISSUE TITLE
Tilt after generate without error

### ISSUE THREAD

**Issue by rossinicolas** [MichalLytek/typegraphql-prisma#105]
i'm trying to run the npx prisma generate related to the source code that i have in github repo and the excecution stop without any error.
In other win10 environment there are not problems.

```prisma
generator client {
  provider = "prisma-client-js"
  // binaryTargets = ["debian-openssl-1.1.x"]
}

generator typegraphql {
  provider = "typegraphql-prisma"
  // binaryTargets = ["debian-openssl-1.1.x"]
  output = "../prisma/generated/type-graphql"
  // emitTranspiledCode = true
}
```

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- Node v14.16.1
- `typegraphql-prisma` 0.13.0
- Prisma 2 2.20.1
- TypeScript 4.2.4

**Comment by MichalLytek** [comment]
Maybe there's some edge case in your schema, please paste it or create a failing repo.

**Comment by rossinicolas** [comment]
schema.prisma:

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
  // binaryTargets = ["debian-openssl-1.1.x"]
}

generator typegraphql {
  provider = "typegraphql-prisma"
  // binaryTargets = ["debian-openssl-1.1.x"]
  output = "../prisma/generated/type-graphql"
  // emitTranspiledCode = true
}

model Post {
  id        Int      @default(autoincrement()) @id
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String   @db.VarChar(255)
  content   String?
  published Boolean  @default(false)
  author    User     @relation(fields: [authorId], references: [id])
  authorId  Int
}

model Profile {
  id     Int     @default(autoincrement()) @id
  bio    String?
  user   User    @relation(fields: [userId], references: [id])
  userId Int     @unique
}

model User {
  id      Int      @default(autoincrement()) @id
  email   String   @unique
  name    String?
  posts   Post[]
  profile Profile?
}

package.json:

{
  "name": "hello-prisma",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^14.14.41",
    "prisma": "~2.20.1",
    "ts-node": "^9.1.1",
    "typegraphql-prisma": "^0.13.0",
    "typescript": "^4.2.4"
  },
  "dependencies": {
    "@prisma/client": "~2.20.1",
    "@types/graphql-fields": "^1.3.3",
    "graphql-fields": "^2.0.3",
    "graphql-scalars": "^1.9.0"
  }
}

**Comment by rossinicolas** [comment]
Using this basic code, i see the following messages before run DEBUG="*" npx prisma generate

 prisma:loadEnv project root found at /home/xxx/Documentos/Proyectos/hello-prisma/package.json +0ms
  prisma:tryLoadEnv Environment variables loaded from /home/xxx/Documentos/Proyectos/hello-prisma/.env +0ms
[dotenv][DEBUG] did not match key and value when parsing line 1: # Environment variables declared in this file are automatically made available to Prisma.
[dotenv][DEBUG] did not match key and value when parsing line 2: # See the documentation for more detail: https://pris.ly/d/prisma-schema#using-environment-variables
[dotenv][DEBUG] did not match key and value when parsing line 3: 
[dotenv][DEBUG] did not match key and value when parsing line 4: # Prisma supports the native connection string format for PostgreSQL, MySQL and SQLite.
[dotenv][DEBUG] did not match key and value when parsing line 5: # See the documentation for all the connection string options: https://pris.ly/d/connection-strings
[dotenv][DEBUG] did not match key and value when parsing line 6: 
Environment variables loaded from .env
  prisma:engines using NAPI: false +0ms
  prisma:engines binaries to download query-engine, migration-engine, introspection-engine, prisma-fmt +0ms
Prisma schema loaded from prisma/schema.prisma
{
  prismaClientDir: '/home/xxx/Documentos/Proyectos/hello-prisma/node_modules/@prisma/client'
}
  prisma:GeneratorProcess 2021-04-23T10:45:15.165Z prisma:client:generator requiredEngine: queryEngine +0ms 


and then, nothing happens and de code is frozen

**Comment by rossinicolas** [comment]
> Maybe there's some edge case in your schema, please paste it or create a failing repo.

https://gitlab.com/rossi.nicolas/hello-prisma.git

it's just a very simple code to test npx prisma generate

**Comment by MichalLytek** [comment]
Unable to reproduce - I run `npm i` and `npx prisma generate`:

```
~/development/github-repos/hello-prisma$ npx prisma generate
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (2.20.1) to ./prisma/generated/client in 69ms

✔ Generated TypeGraphQL integration to ./prisma/generated/type-graphql in 1.48s
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client

import { PrismaClient } from './prisma/generated/client'
const prisma = new PrismaClient()

┌─────────────────────────────────────────────────────────┐
│  Update available 2.20.1 -> 2.21.2                      │
│  Run the following to update                            │
│    npm i --save-dev prisma                              │
│    npm i @prisma/client                                 │
└─────────────────────────────────────────────────────────┘
```

**Comment by rossinicolas** [comment]
![image](https://user-images.githubusercontent.com/30933521/115881559-3f227c00-a422-11eb-9b32-46345ec8d2fc.png)

In my case nothing happend and the type aren't created.
I'm using a fresh ubuntu 20.04 with node v14.16.1 and npm v6.14.12.....for my it's similar to issue #95

**Comment by MichalLytek** [comment]
Can't reproduce. I use Ubuntu 20.04 on WSL2.

Come back with a proper reproduction repo.

**Comment by rossinicolas** [comment]
Dear Michal, i'm writing to tell you that the issue was related to NodeJS. In my ubuntu desktop i had NodeJs installed using Ubuntu Software snap and for any reason the typegraphql-prisma module didn't work. I uninstall NodeJS and install using Bash command line via apt-get and now is working fine.
Thanks in advance.
