### ISSUE TITLE
fix: change default to namespace import in generateGraphQLFieldsImport

### ISSUE THREAD

**Issue by EndyKaufman** [MichalLytek/typegraphql-prisma#118]
https://github.com/MichalLytek/typegraphql-prisma/blob/3322e7cd55e2528525a70aa0d5e41e10a900d324/src/generator/imports.ts#L32

my sample does not work with default, after I change to a namespace, generated code start works fine

![image](https://user-images.githubusercontent.com/4127109/119334825-ff5ee680-bca4-11eb-8f69-02b5d9548a4f.png)

I found this bug after merge upstream and test use in sample application with sample queries and mutation from my readme

commit in my fork -
https://github.com/EndyKaufman/typegraphql-prisma-nestjs/commit/ae7cb21f9cf5cdeb33655ec4657495195f8f96c0

example applications - https://github.com/EndyKaufman/typegraphql-prisma-nestjs-example

sample queries and mutation - https://github.com/EndyKaufman/typegraphql-prisma-nestjs-example/blob/master/README.md

**Comment by MichalLytek** [comment]
You should just use `"esModuleInterop": true`, then it works fine.

**Comment by EndyKaufman** [comment]
oh, I didn't think about it) thanks
