### ISSUE TITLE
Advanced filtering capabilities in nested queries

### ISSUE THREAD

**Issue by macmillen** [MichalLytek/typegraphql-prisma#126]
**Is your feature request related to a problem? Please describe.**
I am currently looking for advanced filtering capabilities to return only certain rows of a nested model in a query. (e.g. filtering out all rows with an `id` ...). To explain better what I mean, please check the following example.

Given the following simplified schema:

``` prisma
model Term {
  translations Translation[]
}

model Language {
  translations Translation[]
}

model Translation {
  term       Term              @relation(fields: [termId], references: [id])
  language   Language          @relation(fields: [languageId], references: [id])
}
```

What i want to achieve in this example is to always return all `Terms` but only with `Translations` that belong to a certain `Language`. I can do that in Prisma with the `include` field like so:

``` ts
await prisma.term.findMany({
  include: {
    translations: {
      where: { languageId: { equals: "ckpvc0l850094bzrjsmr1umcj" } },
    },
  }
})
```

Currently with the generated GraphQL resolvers I am limited to `every`, `none` and `some` filters (see below) which are not sufficient in my case because then it's excluding the `Term` if the `where` clause fails.

``` ts
await prisma.term.findMany({
  where: {
    translations: { every: { languageId: "ckpvc0l850094bzrjsmr1umcj" } },
  },
})
```

**Describe the solution you'd like**
It would be awesome if we could add the `include` parameter to the GraphQL resolvers to make this work. Maybe we could only allow the `where` field in the `include` options in case the other options would cause issues.

**Comment by MichalLytek** [comment]
To filter relations, you just use args for the relations in the graphql query:

```graphql
query {
  findManyTerm {
    translations(where: { languageId: { equals: "ckpvc0l850094bzrjsmr1umcj" }}) {
      # ...
    }
  }
}
```

There's no good way in GraphQL to force a root query to return data with limited relations.

By describing on a more understandable data model: it's an antipattern when your `bestAuthors` root query for blog platform is trying to limit returned `posts` relations data to only include post with rating > 4.0.

It's client responsibility to even do not request user posts at all.
If you want to enforce some settings/data, you can use custom fields like `User -> bestPosts` which won't accept args but will return only the author posts with rating > 4.0.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

**Comment by MaxiSantos** [comment]
@MichalLytek  wow, almost 7 years and I have the same question. I want to accomplish the same thing @macmillen tried.. I want to filter a deep field in a custom resolver I have. https://prisma.typegraphql.com/docs/basics/usage#relations-resolvers in that link you mention `generated relation resolvers also supports providing arguments that allows you to filter` but this dosne't seem to be the case for a `findMany` prisma operation

```js
const stores = await prisma.store.findMany({
        where: {        
          product: {           
            some: {
              status: true,
              productId,
            },
          },
        },
```
This is a search a user has made so I want to return all stores that at least have that product. But I want to filter the list of products to only the requested product. Right now its returning all the products.

I've tried this

```js
 const stores = await prisma.store.findMany({
        where: {
          product: {
            some: {
              status: true,
              productId,
            },
          },
        }
      }).storeProduct({where:{productId}})
```

but it dosen't recognize the `.storeProduct` method. Any suggestion ?

**Comment by MaxiSantos** [comment]
I've tried adding a custom field resolver.. but I've realized this won't work https://prisma.typegraphql.com/docs/advanced/adding-fields since the args I need are dependent on the result of the `prisma.store` query.

**Comment by MaxiSantos** [comment]
@MichalLytek please help me.. I've been playing a bit and now it's working but I don't like it :(

```js
@Resolver(of => Store)
export class CustomStoreResolver {
  // queries and mutations

  @FieldResolver(type => Product, { nullable: true })
  async productFiltered(
    @Ctx() { prisma }: typeof context,
    @Arg("productId", type => Int) productId: number,
    @Root() store: Store
  ) {
    const [filteredProduct] = await prisma.store
      .findUnique({ where: { id: store.id } })
      .storeProduct({ where: { productId } });

    //return store.storeProduct.filter(item => item.productId === productId);
    return filteredStoreProduct;
  }
}
```

By accessing the Root field (in this case the `Store`) I thought I was going to have access to all fields but I only see scalar values. So I'm requesting again the store and this time I see storeProduct and then I can make the filter.

QUESTION: is there a way I can have access to related fields on my FieldResolver ? I need to access a related field in `@Root() store: Store`

The query resolver on the backend is now this:

```js
const stores = await prisma.store.findMany({
        where: {        
          product: {
            some: {
              status: true,
              productId,
            },
          },
        },
        include: {
          product: true
        }
      })
```

And this is the query I send from client

```js
stores(where:{productId:{some:{id:{equals:8}}}}){
    id
    name
    productFiltered(productId: 8){
      storeId
      productId
      name
    }
```
