### ISSUE TITLE
Serialize value for Decimal

### ISSUE THREAD

**Issue by itsnotrisky** [MichalLytek/typegraphql-prisma#144]
**Describe the Bug**
Not sure if it's a bug or intended, but Decimal type is serialized as string shown in the [generator file](https://github.com/MichalLytek/typegraphql-prisma/blob/main/src/generator/generate-scalars.ts).

**To Reproduce**
Have a field type Decimal and `npx prisma generate` will produce `scalars.ts` file for `DecimalJSScalar` with `value.toString()` to serialize it.

**Expected Behavior**
[This issue](https://github.com/prisma/prisma/issues/6049) from prisma repo gave an example to return `value.toNumber()` in this [gist file](https://gist.github.com/matthewmueller/b3ed598f0a9ed8a81dacc969a625dc29) so that graphql clients can consume it as number instead of string.

**Logs**
No logs required.

**Environment (please complete the following information):**

- OS: WSL Ubuntu 20.04
- Node 12.16.3
- `typegraphql-prisma` version 0.14.7
- Prisma version 2.27.0
- TypeScript version 4.3.5

**Additional Context**
No additional context.

**Comment by MichalLytek** [comment]
> This issue from prisma repo gave an example to return value.toNumber() in this gist file so that graphql clients can consume it as number instead of string.

This is not true. Decimal.js can hold values that are not representable using JS number value because of the floating point nature:
```
y = new Decimal('45987349857634085409857349856430985')
y.toNumber()                   // 4.598734985763409e+34
```

It is recommended to use string-based approach for safety.
