### ISSUE TITLE
Add a configuration option to emit original names in decorator options

### ISSUE THREAD

**Issue by mdesousa** [MichalLytek/typegraphql-prisma#156]
Hi, thanks for this awesome library!

I would like to request this option to emit the original names in the decorator options. This is to avoid errors when code is processed by a bundler like `webpack` or `esbuild`.

Please see this for reference: https://github.com/MichalLytek/type-graphql/issues/963#issuecomment-894459659

Thanks!

**Comment by MichalLytek** [comment]
Implemented in 2856cfe 🚀 
It is emitted by default, no need for a config option/flag.

@mdesousa Please let me know if that fixes your issue or we need to also take care about the resolvers methods or type fields.

**Comment by mdesousa** [comment]
Thanks @MichalLytek , will check it out

**Comment by mdesousa** [comment]
@MichalLytek just wanted to confirm that this fixed the issue. Thanks again!
