### ISSUE TITLE
Input Validation via `applyInputTypesEnhanceMap` not working

### ISSUE THREAD

**Issue by defrex** [MichalLytek/typegraphql-prisma#176]
**Describe the Bug**
Given a simple model

```prisma
model Post {
  id    Int    @id @default(autoincrement())
  title String
}
```

and a simple string length validation decorator from `class-validator`

```typescript
applyInputTypesEnhanceMap({
  PostCreateInput: {
    fields: {
      title: [MinLength(10)],
    },
  },
});
```

I would expect the following mutation to return an error.

```graphql
mutation {
  createPost(data: { title: "notten" }) {
    id
  }
}
```

It does not.

**To Reproduce**
Here is a minimal reproduction.
https://github.com/defrex/prisma-typegraphql-input-repro

**Comment by AmirMuha** [comment]
The data you pass into the `createPost` mutation is an argument, you've already added your arbitrary decorator (Length() to the PostCreateInput), now you need to call `applyArgsTypesEnhanceMap()` as well.
example:
```
applyArgsTypesEnhanceMap({
  CreatePostArgs: {
    fields: {
      data: [ValidateNested()] // to validate properties nested in data object which is of type CreateInputPost 
    }
  }
})
```
NOTE that you need to have your InputTypes implemented already (e.g. `applyInputTypesEnhanceMap({....})`).

**Comment by MichalLytek** [comment]
@defrex
> Be aware that in case of class-validator you need to add @ValidateNested decorator to the args classes to trigger validation of the proper input types.

https://prisma.typegraphql.com/docs/advanced/additional-decorators

**Comment by defrex** [comment]
I see. Thanks for clarifying.

**Comment by eduardolundgren** [comment]
@MichalLytek, the input validation functions as explained in this thread, but it seems other middleware aren't working with applyInputTypesEnhanceMap. Could I be overlooking something obvious here?

```ts
applyArgsTypesEnhanceMap({
  CreateOneThreadArgs: {
    fields: {
      data: [ValidateNested()],
    },
  },
});

applyInputTypesEnhanceMap({
  ThreadCreateInput: {
    fields: {
      description: [
        Authorized(Role.SYSTEM_ADMIN), // Does not work, doesn't invoke authChecker
        UseMiddleware((_data, next) => { console.log('description field accessed'); return next(); }), // Does not work
        MinLength(100), // That works fine
      ],
    },
  },
});
```

**Comment by MichalLytek** [comment]
@eduardolundgren There's no middlewares for input or args types.

**Comment by eduardolundgren** [comment]
@MichalLytek, is there a method to validate data against a model before making changes, like ensuring an Application can only be created if the user belongs to a specific membership table (an external validation). For example:

```ts
applyModelsEnhanceMap({
  Application: {
    fields: {
      _all: [
        UseMiddleware(async (data, next) => {
          const { context, root } = data;
          if (await isMemberOfApplication(context, root.id)) {
            return next();
          }
          throw new AuthorizationError('Permission denied. You are not a member of this application.');
        }),
      ],
    },
  },
});
```

The example provided performs well for reading data; however, when mutating data, it first adds the data to the database and then restricts access to the model. It would be great to have a method to intercept and review the data before it is added to the database. I can do that using Row-Level-Security, but wanted to move the logic to the code instead.

**Comment by MichalLytek** [comment]
Please put that middleware on the resolver level - query or mutation.

**Comment by eduardolundgren** [comment]
@MichalLytek Yes, I did, and that makes sense. The problem is that the arguments of the resolver level - query or mutation have several permutation possibilities where the use can specify the id of the entity querying or mutating. It can come as a normal id, or inside a where, or inside a connect, or inside a connectOrCreate. In the end it is nearly impossible to validate all those permutations, to extract the ids of the entities being queried or mutated in order to validate safely.
