### ISSUE TITLE
Add example using Prisma and NestJS

### ISSUE THREAD

**Issue by sandbox-apps** [MichalLytek/typegraphql-prisma#179]
**Describe the issue**
NestJS has a built in package of GraphQL that can create classes like resolvers also. Maybe we can create a sample or docu where it shows how can we use generated files by typgraphql into NestJS modules

**Comment by MichalLytek** [comment]
> NestJS has a built in package of GraphQL that can create classes like resolvers also.

NestJS has its own package, with own API that differs from TypeGraphQL.
`typegraphql-prisma` doesn't work with NestJS.

You can use `typegraphql-nestjs` to use TypeGraphQL classes with NestJS:
https://github.com/MichalLytek/typegraphql-nestjs
Examples here:
https://github.com/MichalLytek/typegraphql-prisma/tree/main/examples/4-nest-js
