### ISSUE TITLE
Using String field for id with @default(uuid()) doesn't omit the id field in the create input 

### ISSUE THREAD

**Issue by alainfonhof** [MichalLytek/typegraphql-prisma#189]
**Describe the Bug**
When defining a model:
```
model User {
 id String @id @default(uuid())
 label String
}
```

This will result in:
```
input UserCreateInput {
 id String
 label String
}
```

While in the example in the docs [Hiding Prisma model field in GraphQL schema](https://prisma.typegraphql.com/docs/advanced/hiding-field) it shows the id field is omitted. When defining a User model with `id Int @id @default(autoincrement())` it does seem to result in the expected behaviour. 

**Environment:**
- Node 14.16
- `typegraphql-prisma` version 0.16.0
- Prisma version 3.0.1
- TypeScript version 4.43

**Comment by MichalLytek** [comment]
Please check `UserCreateInput` type from Prisma Client, e.g. when you call `prisma.user.create()`.

`typegraphql-prisma` only translates Prisma DMMF into classes, it doesn't add or hide properties when it's autoincrement or uuid.

**Comment by alainfonhof** [comment]
Maybe I don't understand it correctly but when I have the following `prisma.schema`:
```
generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "../prisma/generated/type-graphql"
}

model UserA {
  id    Int    @id @default(autoincrement())
  label String
}

model UserB {
  id    String @id @default(uuid())
  label String
}
```

After running `npx prisma generate` it results in the following types in the `prisma-client`:
```
export type UserACreateInput = {
 label: string
 }
export type UserACreateManyInput = {
 id?: number
 label: string
 }
export type UserBCreateInput = {
 id?: string
 label: string
 }
export type UserBCreateManyInput = {
 id?: string
 label: string
 }
 ```
 
The type `UserACreateInput` has `id` omitted while for UserB this isn't the case, right? It also seems to have inconsistency between `UserACreateInput` and `UserACreateManyInput`.

**Comment by MichalLytek** [comment]
It's normal for normal create and create many.

But yes, it looks like a Prisma issue that id still exist for the default uuid id string field. 
Please report on theirs repo.

**Comment by alainfonhof** [comment]
What would be the best approach to hide the `id` field from certain input types like `UserCreateManyInput`,  `UserCreateInput` and `UserUpdateInput`? The doc line `/// @TypeGraphQL.omit(input: true)` will not work because it also omits the `id` field from `UserWhereUniqueInput`. 
I have been looking into [Additional decorators for CRUD resolvers and Prisma classes and fields](https://prisma.typegraphql.com/docs/advanced/additional-decorators) and [Omit](https://www.typescriptlang.org/docs/handbook/utility-types.html#omittype-keys) but it is not clear to me  if this is the right approach. 
How would I go about hiding the `id` field for certain input types without editing the generated `type-graphl`?

**Comment by MichalLytek** [comment]
It's not possible for now.

**Comment by MichalLytek** [comment]
@alainfonhof Have you reported the bug with id field in create input on Prisma repo?

**Comment by ShawkiS** [comment]
hey!! any updates on this?
