### ISSUE TITLE
New emitOnly feature not working as I expected

### ISSUE THREAD

**Issue by JClackett** [MichalLytek/typegraphql-prisma#193]
Not sure if this is a bug or by design, so happy to move this to discussions if necessary.

In our projects we use the models, enums, inputs and never the generated resolvers. However we often use the args that would be passed into the prisma query. This is extremely useful as we dont have to write all the take, skip, orderBy things. However this only gets generated if "crudResolvers" is added. I was wondering if it was possible to also generate just the "args".

Here's an example of some code and how we use args.

```ts
class ThingResolver
  @Query(() => Thing, { nullable: true })
  async thing(@Args() args: FindFirstThingArgs): Promise<Thing | null> {
   // some custom business logic typically goes here
    return await prisma.thing.findFirst({ ...args, ...someCustomArgs })
  }

  @Query(() => [Thing])
  async things(@Args() args: FindManyThingArgs): Promise<Thing[]> {
   // some custom business logic typically goes here
    return await prisma.thing.findMany({ ...args,  ...someCustomArgs })
  }
}
```

So I know right now it looks like just the generated crud resolvers, but a lot of the time we have custom logic and args, so we cant rely just on the generated resolvers, but the generated args save us soooo much time.

It would be great if we could get those args generated separately, or is too coupled to the crud resolvers in your opinion?

Thanks for the work on this!

**Comment by MichalLytek** [comment]
Please keep the discussion in #148 where you find the answer 🔒
