### ISSUE TITLE
CRUD's filter doesn't work as expected, the "OR" has an "AND" behavior.

### ISSUE THREAD

**Issue by melanke** [MichalLytek/typegraphql-prisma#197]
**Describe the Bug**
CRUD's filter doesn't work as expected, the "OR" has an "AND" behavior. If you filter by a single field it finds some results, if you filter by a second field using "OR" and an unfulfilled statement it doesn't find anything.

**To Reproduce**
This Query returns some results:
```graphql
query {
  posts(where: {title: {contains:"incuba"}}) {
    title
    body
    authorId
  }
}
```

This query don't:
```graphql
query {
  posts(where: {title: {contains:"incuba"}, OR: {authorId: {equals: 29}}}) {
    title
    body
    authorId
  }
}
```

This query also don't return any result:
```graphql
query {
  posts(where: {title: {contains:"incuba"}, OR: {body: {contains: "something wrong"}}}) {
    title
    body
    authorId
  }
}
```

**Expected Behavior**
The subsequent filters should only add new results instead of removing.

**Environment (please complete the following information):**

- OS: Windows 10
- Node: v14.17.3
- `typegraphql-prisma` version: 0.16.0
- Prisma version: 3.1.1
- TypeScript version: 4.4.3

**Comment by MichalLytek** [comment]
Please read about building Prisma queries first.
`typegraphql-prisma` is a thin wrapper around Prisma Client.
