### ISSUE TITLE
Import all generated code

### ISSUE THREAD

**Issue by jlavric** [MichalLytek/typegraphql-prisma#20]
Hi! After trying to adopt Prisma 2 and migrate my last few years of work to it I was little tired. Prisma 1 was really handy. Today I found this project and it is life saver. Michal excellent work!! Thank you!
My question is maybe the word of lazy dev but I is there a way to import all generated code into schema builder.
`
...
`import * as typegraphql from "./prisma/generated/type-graphql";`

...
```
async function main() {
  const schema = await buildSchema({
    resolvers: [
      typegraphql.resolvers      
    ],
    emitSchemaFile: path.resolve(__dirname, "./generated-schema.graphql"),
    validate: false,
  });
```
`
I could write anothe index.ts and export all the resolvers, but I guess that this could generated too?
Thank you again for your work!

**Comment by MichalLytek** [comment]
Barrel export of all resolvers and args/model/input classes as a kinda namespace is on my roadmap 😉 

For now you can try to use `index.ts` files in `crud` and other subfolders - I haven't tested if it really works.

**Comment by MichalLytek** [comment]
Closing by 381722e 🎉

**Comment by jlavric** [comment]
I am sorry I was 'off' for quite a long time :)
Thank you for this ehancement it works superb!
