### ISSUE TITLE
Prisma.Decimal serialization sometimes fails

### ISSUE THREAD

**Issue by dbismut** [MichalLytek/typegraphql-prisma#201]
**Describe the Bug**
I have a schema with a `price` field, typed as a Decimal. When I run a query with that field, I sometimes get the following error:

```
[DecimalError] Invalid argument: object. Expected Prisma.Decimal instance
```

This happens in development mode (I haven't tested production).

**To Reproduce**
I have no idea how to reproduce this, but it does happen repeatedly. The first time I launch the query, it runs fine, but after a while, I get the error.

I have manually patched `generate-scalars.js` from this lib to add the following `console.log`:

```js 
serialize: (value: unknown) => {
  console.log(value, value instanceof Prisma.Decimal, value.__proto__)
  if (!(value instanceof Prisma.Decimal)) {
    throw new Error(`[DecimalError] Invalid argument: ${typeof value}. Expected Prisma.Decimal instance.`);
  }
  return value.toString();
}
```

When it works, the result is:

```
1200, true, { toStringTag: '[object Decimal]', ... }
```

When it doesn't, the result is:

```
1200, false, { toStringTag: '[object Decimal]', ... }
```

I have compared value prototypes, and they both look the same. I'm not sure what happens there, I'm sorry I can't give a clear reproduction schema, I know this is infuriating.

**Logs**
```
{
    "message": "[DecimalError] Invalid argument: object. Expected Prisma.Decimal instance.",
    "path": [
        "orders",
        0,
        "price"
    ],
    "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
            "stacktrace": [
                "Error: [DecimalError] Invalid argument: object. Expected Prisma.Decimal instance.",
                "    at GraphQLScalarType.serialize (webpack-internal:///./src/server/graphql/generated/type-graphql/scalars.ts:17:13)",
                "    at completeLeafValue (/Users/dbismut/repos/ateliers/node_modules/graphql/execution/execute.js:653:37)",
                "    at completeValue (/Users/dbismut/repos/ateliers/node_modules/graphql/execution/execute.js:578:12)",
                "    at completeValue (/Users/dbismut/repos/ateliers/node_modules/graphql/execution/execute.js:556:21)",
                "    at /Users/dbismut/repos/ateliers/node_modules/graphql/execution/execute.js:469:16",
                "    at async Promise.all (index 1)",
                "    at async Promise.all (index 0)",
                "    at async Promise.all (index 0)",
                "    at async execute (/Users/dbismut/repos/ateliers/node_modules/apollo-server-core/dist/requestPipeline.js:204:20)",
                "    at async processGraphQLRequest (/Users/dbismut/repos/ateliers/node_modules/apollo-server-core/dist/requestPipeline.js:138:28)"
            ]
        }
    }
}
```

**Environment (please complete the following information):**

- OS: Mac OS 12.0.1
- Node: v14.18.1
- `typegraphql-prisma`: 0.16.4
- Prisma version: 3.3.0
- TypeScript version: 4.4.4

**Additional Context**
I'm using Next JS with `urql`.

**Comment by dbismut** [comment]
Maybe this issue can help: https://stackoverflow.com/questions/53092547/instanceof-returns-false-for-same-class-after-serialization?rq=1

**Comment by MichalLytek** [comment]
If Prisma does not return `Prisma.Decimal`, I think you need to open a bug report on `prisma` repository 😝 

As you can see, the scalar is fairly simple, so I can't do anything about that.

**Comment by dbismut** [comment]
I think the `instanceof` condition is what makes it fail as serialization seems to break it as explained in the SO issue. I can try to see if there's another way to make the condition work while being relevant?

**Comment by MichalLytek** [comment]
>  as explained in the SO issue

This issue is about Java, not JS...

**Comment by dbismut** [comment]
Aren't Java and JavaScript the same thing 🤪? Sorry I should stop trying to work from my phone!

Nevertheless I'll investigate since the `instanceof` condition seems to be the culprit. 

Btw incredible job with the lib. I wasn't familiar with decorators and had quite a hard time with the API initially but it's really growing on me!

**Comment by dbismut** [comment]
Would it be acceptable to proceed to these changes:

```diff
-if (!(value instanceof Prisma.Decimal)) {
+if (!Prisma.Decimal.isDecimal(value)) {
  throw new Error(\`[DecimalError] Invalid argument: \${typeof value}. Expected Prisma.Decimal instance.\`);
}
```

This solves it for me.

See:

https://github.com/MikeMcl/decimal.js/blob/1bcf06742997df3e61ac0fc44ff7845314ec7813/decimal.js#L4534-L4536

It looks like `instanceof` condition isn't always sufficient.

If that's fine with you I can make a PR.

**Comment by MichalLytek** [comment]
Ok it makes sense, thought is still weird 😉 

![opera_mKkODG5XtP](https://user-images.githubusercontent.com/10618781/140039510-534e7d56-ad0f-4229-ab53-d60839048362.png)

I will change that in today's release.

**Comment by dbismut** [comment]
Thanks! Btw, quick related question — sorry if this is not the right place — but would there be a way for me to override that `DecimalJSScalar` scalar so that the schema would use my scalar instead of this one? I tried using `scalarsMap` in `buildSchema` but that doesn't it seem to work as I thought.

The main reason why I want to do this is because I'm returning `"__unauthorized__"` on fields that aren't authorized, and that makes serialization of a `Decimal` fail since `"__unauthorized__"` isn't obviously a `Decimal` instance.

Thanks a million.

**Comment by MichalLytek** [comment]
There's no such feature available. And you should return `null` or throw an error instead of some custom patterns like `"__unauthorized__"`
