### ISSUE TITLE
Additional decorators Not Working

### ISSUE THREAD

**Issue by NitelPhyoe** [MichalLytek/typegraphql-prisma#219]
I setup **middleware** like this

```ts
 const LogAccess: MiddlewareFn = async ({ context, info }, next) => {
	const username = context || "guest";
	console.log(
		`Logging access: ${username} -> ${info.parentType.name}.${info.fieldName}`
	);
	return next();
};



applyResolversEnhanceMap({
	User: {
		createUser: [
			UseMiddleware(LogAccess),
		],
	},
});

```

when i run this mutation

```gql
mutation {
  createUser(
    data: { name: "testEn1", email: "enc1@te.com", password: "this is plain" }
  ) {
    id
    name
  }
}

```

there is no log on console and it seen like not working 
![image](https://user-images.githubusercontent.com/45162993/144984555-3e000290-0f47-4661-b9e9-20607d9d69de.png)

i use node 14 lts and my package.json is
```json
    "next": "12.0.4",
    "class-validator": "^0.13.2",
    "graphql": "^15",
    "graphql-fields": "^2.0.3",
    "graphql-scalars": "^1.13.6",
    "graphql-upload": "^13.0.0",
    "apollo-server-micro": "^3.5.0",
    "@prisma/client": "^3.6.0",
    "@types/graphql-fields": "^1.3.4",
    "reflect-metadata": "^0.1.13",
    "tslib": "^2.3.1",
    "type-graphql": "^1.1.1",
    "prisma": "^3.6.0",
    "typegraphql-prisma": "^0.18.1",
```

**Comment by MichalLytek** [comment]
And I can see additional decorators are working:
```ts
applyRelationResolversEnhanceMap({
  Movie: {
    _all: [
      UseMiddleware(({ info }, next) => {
        console.log(`${info.parentType.name}.${info.fieldName} field accessed`);
        return next();
      }),
    ],
  },
});
```
```graphql
{
  movies {
    title
    director {
      firstName
      lastName
    }
  }
}
```
```
prisma:query SELECT 1
prisma:query SELECT "public"."Movie"."directorFirstName", "public"."Movie"."directorLastName", "public"."Movie"."title" FROM "public"."Movie" WHERE 1=1 OFFSET $1
Movie.director field accessed
Movie.director field accessed
Movie.director field accessed
```

@NitelPhyoe Please create a minimal reproducible code example. Prisma model should be minimal and use sqlite.

**Comment by NitelPhyoe** [comment]
You can access my repo:
[Zaypyay](https://github.com/NitelPhyoe/zaypyay)

**Comment by MichalLytek** [comment]
This is not a minimal repo. I don't have time to debug your whole next.js project. Try to isolate the code, then you will find what's in your setup causing this issues.

**Comment by NitelPhyoe** [comment]
My apologies, I found out the problem.
@MichalLytek , here is minimal repo: https://github.com/NitelPhyoe/test-prisma-tgql

apply Additional decorators other than nextjs api route (page/api/graphql.ts) will not work. I don't know why we cannot apply custom decorators on separate file.

**Comment by NitelPhyoe** [comment]
this will not work [separate file](https://github.com/NitelPhyoe/test-prisma-tgql/blob/main/lib/customDecorator.ts)
this will work [api file](https://github.com/NitelPhyoe/test-prisma-tgql/blob/main/pages/api/graphql.ts)

**Comment by MichalLytek** [comment]
This has to be applied before you call `buildSchema`. Othewise the graphql schema is build without those info.

**Comment by NitelPhyoe** [comment]
I got it. I close this issuse. Thanks
