### ISSUE TITLE
Hang when using yarn 2

### ISSUE THREAD

**Issue by rizkyramadhan** [MichalLytek/typegraphql-prisma#22]
When I use yarn 2 to run basic example, it just hang in:

`Prisma Schema loaded from prisma\schema.prisma`

to reproduce: 

1. Clone basic-1 example
2. remove package-lock.json
3. install yarn and run `yarn set version berry`
4. run `yarn` on that directory
5. run `yarn prisma generate`

prisma will hang generating typegraphql-prisma, but when I comment `generator typegraphql ` it runs fine.

**Comment by rizkyramadhan** [comment]
This does not happen in npm and yarn 1, But I need yarn 2 workspace for my project.

**Comment by MichalLytek** [comment]
Yarn 2 PnP system is complicated and not compatible with plenty of tools.

I don't plan to spend time on this soon, leaving the issue opened as a feature request.

**Comment by merceyz** [comment]
You can use the node-modules linker until it's fixed
```
yarn config set nodeLinker node-modules && yarn
```
They use native executables which makes it really hard to debug the issue

**Comment by rizkyramadhan** [comment]
> You can use the node-modules linker until it's fixed
> 
> ```
> yarn config set nodeLinker node-modules && yarn
> ```
> 
> I looked into it but they use native executables which makes it really hard to debug the issue

Thanks for the suggestion, but I did the hard way. I forked @prisma/client and typegraphql-prisma, create new workspace for it, and then rewire it so it can talk to each other, it pays off for the long run
