### ISSUE TITLE
Adding a description and omit breaks generate script

### ISSUE THREAD

**Issue by joesaunderson** [MichalLytek/typegraphql-prisma#239]
**Describe the Bug**
When I add a `/// description` and `/// @TypeGraphQL.omit(input: true)` to a field in prisma, the `prisma generate` command hangs as does not complete.

**To Reproduce**

Add this to `schema.prisma`

```prisma
model Person {
  /// The ID of the person
  id        String   @id @default(cuid())
  /// The email of the person
  email     String
  /// The firstname of the person
  firstname String
  /// The surname of the person
  surname   String
  /// The created date of the person
  /// @TypeGraphQL.omit(input: true)
  createdAt DateTime @default(now())
  /// The updated date of the person
  /// @TypeGraphQL.omit(input: true)
  updatedAt DateTime @updatedAt
  /// The users the person is associated with
  users     User[]
}
```

**Expected Behavior**
The command finishes, and the correct types are outputted.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occurred.

**Environment (please complete the following information):**

- OS: Mac OS (Apple Silicon)
- Node v16.13.2
- `typegraphql-prisma` version ^0.18.4
- Prisma version 3.8.0
- TypeScript version (e.g. 4.2.2)

**Additional Context**

**Comment by MichalLytek** [comment]
> Prisma version 3.8.0

Please read the release notes more carefully.
You need Prisma v3.8.1 to work with typegraphql-prisma 0.18.4.

I have
```
/// renamed field doc
/// @TypeGraphQL.field(name: "firstName")
name        String?
```
in my working dir and no issues with Prisma generator.
