### ISSUE TITLE
Authorization on generated resolvers

### ISSUE THREAD

**Issue by SheaBelsky** [MichalLytek/typegraphql-prisma#24]
First off, I love this library and how seamlessly it works with Prisma!

I'm finding myself needing to basically re-implement resolvers that have been generated with `npx prisma generate` because I need to add some additional Authorization to them. The TypeGraphQL documentation lists how I could go about adding authorization on custom resolvers, but is there a way to do it for resolers that TypeGraphQL-Prisma generates? Otherwise, I'd need to basically reimplement resolvers for things that I want to restrict access to.

**Comment by MichalLytek** [comment]
Duplicate od #11 🔒
