### ISSUE TITLE
Support for prisma 3.9.x

### ISSUE THREAD

**Issue by FloydJohn** [MichalLytek/typegraphql-prisma#244]
The prisma team recently released version 3.9.0 and 3.9.1 of their packages, including `prisma` and `@prisma/client`.
If the packages are updated to the latest version, typegraphql-prisma fails to run as the dependency is pinned in the [package.json](https://github.com/MichalLytek/typegraphql-prisma/blob/main/package.json).

The detailed error message is:
```
Error: Looks like an incorrect version "3.9.1" of the Prisma packages has been installed. 'typegraphql-prisma' works only with selected versions, so please ensure that you have installed a version of Prisma that meets the requirement: "~3.8.0". 
Find out more about that requirement in the docs: https://prisma.typegraphql.com/docs/advanced/prisma-version
```

I can open a PR bumping all prisma dependencies to `"~3.9.1"`, but I would like to ask first if
* Bumping the dependencies could break some features in a way not detectable with the included automated tests
* I can update the link on the error message to the correct path: [https://prisma.typegraphql.com/docs/basics/prisma-version](https://prisma.typegraphql.com/docs/basics/prisma-version)

**Comment by MichalLytek** [comment]
Just use `SKIP_PRISMA_VERSION_CHECK=true` and wait for the update.
