### ISSUE TITLE
Empty array is being returned on findMany query used with take argument 

### ISSUE THREAD

**Issue by nitheshb** [MichalLytek/typegraphql-prisma#248]
**Describe the Bug**
Empty array is being returned,When tried to retrieve rows from related tables with take condition. Parent rows and values are being retrieved successfully

**To Reproduce**
Run Below query:
findManyParentTab(take: 2){
name
location
childTable1{
childname
childlocation
}
}

result:

[
{'name': 'Arya',
'location': 'winterfall',
childTable1: []},
{'name': 'Tyrion',
'location': 'Lanister',
childTable1: []},
]

**Expected Behavior**
childTable1 should not be empty. it should return the values form childTable1

**Logs**

**Environment (please complete the following information):**

- OS: Mac os 
- Node: v16.13.2
- Package version 1.1.1
- TypeScript version (e.g. 2.8.2)

**Additional Context**

**Comment by MichalLytek** [comment]
What is your setup code? Have you enabled relation resolvers?
https://prisma.typegraphql.com/docs/basics/usage#relations-resolvers

**Comment by MichalLytek** [comment]
Unable to reproduce the issue:

```prisma
model User {
  id    Int    @id @default(autoincrement())
  email String @unique
  posts Post[]
}

model Post {
  id      Int    @id @default(autoincrement())
  title   String
  authors User[]
}

```

```graphql
query Take {
  users(take: 1) {
    id
    email
    posts {
      id
      title
      authors {
        id
        email
      }
    }
  }
}
```

```json
{
  "data": {
    "users": [
      {
        "id": 1,
        "email": "fake2@gmail.com",
        "posts": [
          {
            "id": 1,
            "title": "Post title 2",
            "authors": [
              {
                "id": 1,
                "email": "fake2@gmail.com"
              },
              {
                "id": 3,
                "email": "fake1@gmail.com"
              }
            ]
          },
          {
            "id": 2,
            "title": "Post title 3",
            "authors": [
              {
                "id": 1,
                "email": "fake2@gmail.com"
              },
              {
                "id": 2,
                "email": "fake3@gmail.com"
              }
            ]
          }
        ]
      }
    ]
  }
}
```
