### ISSUE TITLE
Error: Generator at node ./node_modules/typegraphql-prisma/generator.js could not start

### ISSUE THREAD

**Issue by AviBueno** [MichalLytek/typegraphql-prisma#25]
Happens because generator.js resides in
`./node_modules/typegraphql-prisma/lib/generator.js` not in
`./node_modules/typegraphql-prisma/generator.js`

package.json:

    "@prisma/cli": "^2.10.1",
    "@prisma/client": "^2.10.1",
    "typegraphql-prisma": "^0.8.3"

output:

```
Error: Generator at node ./node_modules/typegraphql-prisma/generator.js could not start:

internal/modules/cjs/loader.js:968
  throw err;
  ^
Error: Cannot find module '/path/to/project/node_modules/typegraphql-prisma/generator.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by MichalLytek** [comment]
Please show your `schema.prisma` file (generators blocks)

**Comment by AviBueno** [comment]
Turns out it's pointing to the above specified path in our schema.prisma file.
Evidently `generator.js` shifted location.
Thanks, closing.

**Comment by MichalLytek** [comment]
@AviBueno You should just use package name:
`provider = "typegraphql-prisma"`
https://github.com/MichalLytek/typegraphql-prisma/blob/main/Readme.md#configuration

**Comment by AviBueno** [comment]
@MichalLytek yes, that's what I did. Thanks.
Before that it was some pre-historic `provider = "node ./node_modules/typegraphql-prisma/generator.js"` (code which I inherited).

**Comment by omar-dulaimi** [comment]
@MichalLytek Im running into the same issue using an example that was working before.

Here's the schema file:

```
generator client {
  provider = "prisma-client-js"
}

generator typegraphql {
  provider = "typegraphql-prisma"
}

datasource db {
  provider = "sqlite"
  url      = "file:./dev.db"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}

```

And the error message:

```

Prisma schema loaded from prisma/schema.prisma
Error: Generator at typegraphql-prisma could not start:

/bin/sh: 1: typegraphql-prisma: not found
```

**Comment by omar-dulaimi** [comment]
@MichalLytek 
It was caused by a colon in the name of a parent folder like this:

`./usr/examples 3:58/typegraphql-example`

removing the colon fixed the issue.
