### ISSUE TITLE
Treat @id fields in schema as ID type in GraphQL

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/typegraphql-prisma#26]
I have a schema that is using `@id @default(cuid())` as ID column, but TypeGraphQL is setting this field as a String, not as a ID.

Is there any way to tell TypeGraphQL to set the id field type of the prisma schema to the ID Type?

**Comment by MichalLytek** [comment]
There's no real difference between `ID` and `String` in GraphQL. Both are represented as string, the `ID` is only to inform it's not a human-readable value.

**Comment by JohannesKlauss** [comment]
Ah ok. I always thought that apollo is looking for an id field to cache the document it correctly.

**Comment by MichalLytek** [comment]
No, it just looks for `id` property:

![image](https://user-images.githubusercontent.com/10618781/98248429-307c0180-1f75-11eb-8699-a4e2d1dd1243.png)

**Comment by MichalLytek** [comment]
I realised that before 2.0 launch, Prisma has removed ID and UUID scalars from DDMF, so they are now just an int or string fields.

It makes no sense to convert them to GraphQL ID as it would be an inconsistent behavior comparing to multi-field ids (`@@id`). So I will leave it as is, unless there is some big feature behind ID scalars or strong demand for it.

**Comment by strazi** [comment]
Regarding this issue, with ids being treated as strings, we have generated inputs like:

```id?: StringFilter | undefined;```

Whereas in the Prisma client, id accepts:

```id?: StringFilter | string```

This means that in the generated inputs, queries on id end up requiring:

```{ id: { equals: $id } }```

Versus the Prisma client that only requires:

``` { id: $id }```

I think the solution is to extend the generated type in my own resolver?

**Comment by MichalLytek** [comment]
@strazi GraphQL doesn't have union inputs so it can't be as flexible as Prisma TS API. If you want to get rid of all other options of string filter, you need to create your own type with a directly stored value.

**Comment by strazi** [comment]
Thank you for clarifying!

**Comment by tsteenkamp** [comment]
Is there a possibility to change this behaviour? I have a couple of different services implementing the same interface which in the end will be stitched together in a API gateway. That obviously won't work if some services have all `id` fields of type `String!` and others use `id: ID!`.

Maybe something like `/// @TypeGraphQL.field(type: "ID")` would be possible?

**Comment by MichalLytek** [comment]
@tsteenkamp I think we can do a `emitIdAsIDType = true` generator config option 🤔 
DMMF provides `"isId": true` info which we can use.

**Comment by MichalLytek** [comment]
Fixed by 6b9d7e3 🔒
