### ISSUE TITLE
Cannot Determine GraphQL Input Type for Generated Args

### ISSUE THREAD

**Issue by topbloc-beiswenger** [MichalLytek/typegraphql-prisma#265]
**Describe the Bug**

Currently seeing the following error when using generated types in the `buildSchema` function:
```
/node/api/node_modules/type-graphql/dist/schema/schema-generator.js:540
            throw new errors_1.CannotDetermineGraphQLTypeError("input", target.name, propertyName, parameterIndex, argName);
                  ^
CannotDetermineGraphQLTypeError: Cannot determine GraphQL input type for 'take' of 'FindFirstOrganizationArgs' class. Is the value, that is used as its TS type or explicit type, decorated with a proper decorator or is it a proper input value?
    at Function.getGraphQLInputType (/node/api/node_modules/type-graphql/dist/schema/schema-generator.js:540:19)
    at /node/api/node_modules/type-graphql/dist/schema/schema-generator.js:485:28
    at Array.forEach (<anonymous>)
    at Function.mapArgFields (/node/api/node_modules/type-graphql/dist/schema/schema-generator.js:481:29)
    at /node/api/node_modules/type-graphql/dist/schema/schema-generator.js:474:22
    at Array.reduce (<anonymous>)
    at Function.generateHandlerArgs (/node/api/node_modules/type-graphql/dist/schema/schema-generator.js:452:23)
    at /node/api/node_modules/type-graphql/dist/schema/schema-generator.js:398:28
    at Array.reduce (<anonymous>)
    at Function.generateHandlerFields (/node/api/node_modules/type-graphql/dist/schema/schema-generator.js:390:25)
```

I'm currently using Prisma with a monorepo structure where there's an `api` package, a `lambda` package, and a `prisma` package. The `lambda` package need to use PrismaClient and the `api` package needs to use both `PrismaClient` and the generated types from `typegraphql-prisma`. Both the generated types and the `PrismaClient` are exported from a shared `prisma` package.

**To Reproduce**
Here's a repository with the behavior reproduced: https://github.com/topbloc-beiswenger/typegraphql-prisma-monorepo-error

**Expected Behavior**
Expected behavior is for the resolvers to be correctly generated.

**Environment**

- OS: MacOS Monterey v12.2.1
- Node v16.14.2
- `typegraphql-prisma` v0.19.2
- Prisma v3.11.0
- TypeScript v4.6.3

**Comment by MichalLytek** [comment]
The reproduction repository won't even install, you have `tsc` package in dev deps.

You have a weird `"./node_modules/@generated/type-graphql"` output path, have you tried generating the code into a normal folder, with or without `emitTranspiledCode`?

**Comment by topbloc-beiswenger** [comment]
I removed the `output` path line because it was the default anyway, and removed the `tsc` package.

I'm not sure why the `npm install` isn't working. Perhaps different npm versions? If you haven't already, I would try building the docker image to ensure the same environment. 

I've also tried with and without `emitTranspiledCode` and am still running into the same error 😞 

Please let me know if there's any other additional info you need to try to reproduce this error 😄

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
