### ISSUE TITLE
File '.../args.index.ts' is not a module

### ISSUE THREAD

**Issue by eakriulin** [MichalLytek/typegraphql-prisma#28]
I've noticed that after generation I get empty `relations/args.index.ts` file. It causes some bugs when compiling my ts project to js.

Screenshots:
![image](https://user-images.githubusercontent.com/17992903/98443719-352fe980-211e-11eb-93b2-d527daddd6db.png)

![image](https://user-images.githubusercontent.com/17992903/98443721-3eb95180-211e-11eb-9527-d3b0a6a8c88f.png)

Error:
```sh
src/generated/typegraphql-prisma/resolvers/relations/index.ts:2:15 - error TS2306: File '.../src/generated/typegraphql-prisma/resolvers/relations/args.index.ts' is not a module.

2 export * from "./args.index";
```

Dependency versions:
typegraphql-prisma@0.8.3
@prisma/cli@2.10.1
@prisma/client@2.10.1

**Comment by MichalLytek** [comment]
Please show your prisma schema

**Comment by eakriulin** [comment]
@MichalLytek thank you for a quick response, here it is:

```prisma
model User {
    id Int @default(autoincrement()) @id
    app String @default("App")
    name String
    adminInfo AdminUser?

    @@unique([app, appUserId])
}

model AdminUser {
    id Int @default(autoincrement()) @id
    email String
    user User @relation(fields: [userId], references: [id])
    userId Int
}
```

**Comment by MichalLytek** [comment]
@eakriulin looks like it's because your relations are 1-1 so there are no args in the field resolvers 😛 

I'll fix that soon, for now you need to either add another 1-many relation or manually remove the faulty line from generated code.

**Comment by MichalLytek** [comment]
Closing via 6f8bddb 🔒
