### ISSUE TITLE
Type NullableStringFieldUpdateOperationsInput must be an Object

### ISSUE THREAD

**Issue by Morriz** [MichalLytek/typegraphql-prisma#294]
**Describe the Bug**
After generating from this schema:
```prisma
model User {
  id String @id @default(cuid())
  name String?
  email String? @unique
}
```
And creating this mutation in graphiq:
```gql
mutation UpdateUser($name: NullableStringFieldUpdateOperationsInput, $email: String!) {
    updateUser(where: { email: $email }, data: { name: $name }) {
      name
    }
  }

// (it was hinted to turn `$name: String!` into `$name: NullableStringFieldUpdateOperationsInput`, so I did)
```
With these variables:
```json
{"email": "not@ex.ists", "name": "some name"}
```

I get this error about the `name` input:
```
Type NullableStringFieldUpdateOperationsInput must be an Object
```

I have to set the input to this to make it work:
```json
{"email": "not@ex.ists", "name": {"set": "some name"}}
```

I don't understand why.

**Environment (please complete the following information):**

- OS: Mac OS
- Node `16.4.2`
- `typegraphql-prisma` version `0.20.3`
- Prisma version `3.14.0`
- TypeScript version `4.6.4`

**Comment by Morriz** [comment]
Hope to have put it in the right repo this time ;p (Might be the parent repo now that I think about it actually ;)

**Comment by MichalLytek** [comment]
> I have to set the input to this to make it work:

Because Prisma supports more than just overwrite of the field value in the update operation, mostly for numeric fields.
So in order to support this, `typegraphql-prisma` follows this pattern of nested object with `set` and other operations.

See #32 🔒

**Comment by Morriz** [comment]
I found another bug related to this. Will create separate one.
