### ISSUE TITLE
Compatibility issues between typegraphql and prisma enum types

### ISSUE THREAD

**Issue by MichalLytek** [MichalLytek/typegraphql-prisma#3]
I have a property `status` (ENUM) which seems to cause compatibility issues, so I'm required to use Prisma Client's model instead of the one generated by type-graphql. Do you know what this might be?

![image](https://user-images.githubusercontent.com/40734088/94975324-a2de6980-0511-11eb-8325-527803322ba1.png)

If I use the CatalogModel then it works fine, but when I use the one generated by type-graphql, I get the above issue.
![image](https://user-images.githubusercontent.com/40734088/94975542-4fb8e680-0512-11eb-9809-f2b60a5f9bd0.png)

_Originally posted by @jsefiani in https://github.com/MichalLytek/typegraphql-prisma/issues/1#issuecomment-702989587_

**Comment by MichalLytek** [comment]
@MichalLytek Here's a part of my Prisma schema.
`
model Catalog {
  id                       Int          @id @default(autoincrement())
  productId                String?
  productName              String?
  sku                      String?
  primaryCategory          String?
  secondaryCategory        String?
  productUrl               String?
  imageUrl                 String?
  buyUrl                   String?
  shortDescription         String?
  longDescription          String?
  discount                 String?
  discountType             String?
  salePrice                String?
  retailPrice              String?
  beginDate                String?
  endDate                  String?
  brand                    String?
  shippingCost             String?
  queries                  String?
  manufacturerPartNumber   String?
  manufacturerName         String?
  shippingInformation      String?
  availability             String?
  universalProductCode     String?
  classId                  String?
  currency                 String?
  m1                       String?
  pixel                    String?
  miscellaneous            String?
  productType              String?
  size                     String?
  material                 String?
  color                    String?
  gender                   String?
  style                    String?
  age                      String?
  introPurchaseAPRDuration String?
  ongoingPurchaseAPR       String?
  status                   curatestatus @default(unreviewed)
  createdAt                DateTime     @default(now())
}

enum curatestatus {
  accepted
  declined
  pending
  unreviewed
}
`

_Originally posted by @jsefiani in https://github.com/MichalLytek/typegraphql-prisma/issues/1#issuecomment-703704929_

**Comment by MichalLytek** [comment]
@jsefiani
I'm unable to reproduce that in at least `v0.8.0`.

`Catalog` model class is using `typeof curatestatus[keyof typeof curatestatus];` type annotation to comply to Prisma typings:

![image](https://user-images.githubusercontent.com/10618781/95100755-b536ee00-0731-11eb-81bc-e2323aaaa481.png)

**Comment by jsefiani** [comment]
I reproduced it again in `v0.8.0`. 

![image](https://user-images.githubusercontent.com/40734088/95109864-75760380-073d-11eb-9763-7e552d8c9000.png)

Or should I not use the type generated from your library (the Catalog type is generated by your library)?
![image](https://user-images.githubusercontent.com/40734088/95109981-a35b4800-073d-11eb-8041-0064bb209f06.png)

**Comment by MichalLytek** [comment]
Looks like the pattern that worked for objects:

![image](https://user-images.githubusercontent.com/10618781/95110995-28932c80-073f-11eb-9303-79482a8d054c.png)

Stopped working in TS 4.0 for enums:

![Code_5NyRtqsyMw](https://user-images.githubusercontent.com/10618781/95111011-2df07700-073f-11eb-8bef-2fee94d18d23.png)

I'll need to manually emit that type instead of transforming the enum type.

**Comment by jsefiani** [comment]
Okay thanks man!

**Comment by MichalLytek** [comment]
In the meantime you can use Prisma types as the return type:

```ts
@Resolver()
class CatalogResolver {
  @Query(returns => [Catalog])
  async myQuery(@Ctx() { prisma }: Context): Promise<Prisma.Catalog[]> {
    return await prisma.catalog.findMany();
  }
}
```

**Comment by jsefiani** [comment]
Yes, thank you, already doing that for now.

**Comment by MichalLytek** [comment]
Should be fixed by 69fa3bad 🔒 
Please watch the repo releases to be notified about publishing the patch release containing the fix.

**Comment by jsefiani** [comment]
I keep getting below error since I upgraded `@prisma/client`, `@prisma/cli` and `typegraphql-prisma` to minor and patch version 8.1

![image](https://user-images.githubusercontent.com/40734088/95916444-eb671400-0da8-11eb-9003-e8022e22d0c4.png)

Do you know what the issue might be?

**Comment by MichalLytek** [comment]
@jsefiani Use search - you can find #16

**Comment by jsefiani** [comment]
Nice, thank you!
