### ISSUE TITLE
TypeError: Cannot read property 'output' of undefined

### ISSUE THREAD

**Issue by divyenduz** [MichalLytek/typegraphql-prisma#30]
We are writing a E2E test for `typegraphql-prisma` generator. I ran into the following issue while doing that

```
Error: Error: 
TypeError: Cannot read property 'output' of undefined
    at Object.generate [as onGenerate] (/Users/divyendusingh/Documents/prisma/e2e-tests/community-generators/typegraphql-prisma/node_modules/typegraphql-prisma/lib/cli/prisma-generator.js:14:100)
```

# To Reproduce

1. `package.json`

```
{
  "name": "typegraphql-prisma",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@prisma/cli": "2.11.0",
    "typegraphql-prisma": "0.8.4"
  },
  "dependencies": {
    "@prisma/client": "2.11.0"
  }
}

```

2. `schema.prisma`

```
generator typegraphql {
    provider = "typegraphql-prisma"
    output   = "./generated/typegraphql-prisma"
}

model User {
    id    String  @id @default(cuid())
    email String  @unique
    name  String?
}
```

3. `yarn; yarn prisma generate`

Reproduction repo: https://github.com/divyendu-test/typegraphql-generator-issue

**Comment by MichalLytek** [comment]
@divyenduz As stated in Readme, `generator typegraphql ` needs to be declared together with a standard prisma client generator. Otherwise there's no DMMF to work on 😅

**Comment by divyenduz** [comment]
That fixes it indeed. Thanks. This docs page might need to be updated with this info https://typegraphql.com/docs/prisma.html

Closing this issue :)
