### ISSUE TITLE
Integration with prisma 4

### ISSUE THREAD

**Issue by valerii15298** [MichalLytek/typegraphql-prisma#301]
Prisma 4 just got released. Would be amazing for type-graphql to work with prisma 4.

Is type-graphql going to integrate with prisma 4, right?

**Comment by MichalLytek** [comment]
I'm in a direct contact with the Prisma team. The upgrade should be fairly easy. Just give me a bit more time than a few hours.

**Comment by valerii15298** [comment]
@MichalLytek  Thank You!!!!
Very great support of your libraries!
Will close this one when the upgrade will be done, so that people can see there is work going on.

**Comment by valerii15298** [comment]
![image](https://user-images.githubusercontent.com/44531564/176251303-b143792e-ba25-40e7-9fa0-f33afaf7e066.png)
Also I suggest to not forget update `about` info in github repo. Since we have now integration with prisma 3 and soon will have with prisma 4. :)

**Comment by janpio** [comment]
(We are slowly transitioning to calling ourselves just "Prisma ORM" again, as Prisma 1 fades to nothing...)

**Comment by MichalLytek** [comment]
The updgrade has been done and the new package version `v0.21.0` has been released 🚀 

Be aware of the breaking changes described in the release notes 👀 

@valerii15298 The project info on GitHub has been updated too 😉

**Comment by valerii15298** [comment]
That is awesome.
Thank you for your work @MichalLytek !!!
