### ISSUE TITLE
Omit fields from composite type fields

### ISSUE THREAD

**Issue by adamwimmj** [MichalLytek/typegraphql-prisma#303]
**Is your feature request related to a problem? Please describe.**
I use prisma with mongodb so I have embedded documents where I define composite types in the schema. It doesn't look like I can omit some fields of a composite type using `/// @TypeGraphQL.omit(output: true)` above a field.

**Describe the solution you'd like**
Is there a way to omit fields from composite types please?

**Comment by MichalLytek** [comment]
Thanks for reporting this! 🙏 

Looks like it's an issue on the Prisma side:
https://github.com/prisma/prisma/issues/18551

**Comment by MichalLytek** [comment]
Should be fixed by `prisma@4.16.0` 🔒 

@adamwimmj Please let me know if the issue still occurs for you 😉
