### ISSUE TITLE
Full text search capability

### ISSUE THREAD

**Issue by lgharibashvili** [MichalLytek/typegraphql-prisma#311]
Currently TypeGraphQL-Prisma does not seem to generate 'search' property in StringFilter. This property is available in Prisma when full-text search is enabled.

Relevant docs:
https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#sort-by-relevance-postgresql
https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search#querying-the-database

Solution would be for TypeGraphQL-Prisma to add 'search' property to generated StringFilter whenever full-text search is enabled and to also add '_relevance' property to generated order by input types.

If needed I can do a PR with necessary modifications.

**Comment by MichalLytek** [comment]
Cannot reproduce, all is generated propely for me when I enable `previewFeatures = ["fullTextSearch"]` and using Postgres 👀

**Comment by lgharibashvili** [comment]
You are right it was an error from my side
