### ISSUE TITLE
Error: Cannot find module '@generated/type-graphql'

### ISSUE THREAD

**Issue by omarragi** [MichalLytek/typegraphql-prisma#314]
**Describe the issue**
When we set NODE_ENV to production on heroku we get this error
Error: Cannot find module '@generated/type-graphql'
we can see from our logs that it's generated already and seems to be removed after the build
how to tell we want to keep this folder in production? or we better change the generation outside node_modules?

**Comment by MichalLytek** [comment]
> or we better change the generation outside node_modules?

yes
