### ISSUE TITLE
Nullable string changed behavior

### ISSUE THREAD

**Issue by AviBueno** [MichalLytek/typegraphql-prisma#32]
Trying to upgrade from Prisma 2.5.1 to a newer version for quite a while with no luck so versions drifted already.
Now trying to upgrade:

### From:
```
"@prisma/cli": "^2.5.1",
"@prisma/client": "^2.5.1",
"typegraphql-prisma": "^0.5.0"
```

Where this (barebone version of the) code was generated:
```
class UpdateInput {
  text?: string | undefined;
}
```

And this intuitive code used to work:
```
const data: UpdateInput = {
  text: 'some text'
};
const text = data.text;
``` 

### To:
```
"@prisma/cli": "^2.11.0",
"@prisma/client": "^2.11.0",
"typegraphql-prisma": "^0.8.4"
```

Where the generated code got modified to:

```
class NullableStringFieldUpdateOperationsInput {
  set?: string | undefined;
}

class UpdateInput {
  text?: NullableStringFieldUpdateOperationsInput | undefined;
}
```

And this code doesn't work anymore:
```
const data: UpdateInput = {
  text: 'some text'
};
const text = data.text;
```

### My question:
Is it correct that at this point the code should be written in this less-intuitive way:
```
const data: UpdateInput = {
  field: { set: 'some text' }
};
const text = data.text?.toString();
```

Or am I missing something and there's a way to use it intuitively?

* This is a non-trivial change and I'd like to verify that our code base won't break.

**Comment by MichalLytek** [comment]
That's how Prisma has changed their API to support atomic operations.
GraphQL doesn't have input unions so it can't support both plain and nested object ways like Prisma client.

For now, `typegraphql-prisma` is tightly coupled to DMMF shape of action, inputs and other types. When their API becomes stable and this generator package will have other features done, we can investigate the possibility to make some changes in the inputs shape, like omit `set` for string fields.

**Comment by AviBueno** [comment]
The original issue is still a serious blocker for us.

Looking for solutions I bumped into this issue https://github.com/graphql-nexus/nexus-plugin-prisma/issues/830, pointing to this PR https://github.com/graphql-nexus/nexus-plugin-prisma/pull/899

Current question is: Could typegraphql-prisma introduce similar support for an `atomicOperations` boolean?

**Comment by MichalLytek** [comment]
Of course it's possible to introduce similar config flag, like I did recently with unchecked scalars:
https://github.com/MichalLytek/typegraphql-prisma/blob/v0.10.3/Readme.md#unchecked-scalars-input

Unfortunately, I can't declare any ETA as there are a lot of other features and fixes higher on my priority list.
However, if it's a really a serious blocker for you, feel free to make a PR with support for such config flag 😉

**Comment by AviBueno** [comment]
Exactly the answer I was afraid of :)

Can't tell if or when I'll be able to address this, but for the sake of conversation could you maybe share your thoughts on the line of attack here / pointers / where to focus?

**Comment by MichalLytek** [comment]
I haven't explored that topic yet. If DMMF contains the alternative shape, we can select other type when detected the input type with `set` field in the transform step. Otherwise it will require manually creating the type (altering nested input to scalar) on the fly 🤔 I hope that Prisma client have union input so we can pass the value directly without transforming it back to object.

**Comment by AviBueno** [comment]
[Took a look at the code and realized this will be too deep a dive for me at this point]

Peeping at the implementation I referred to, it seems that they are [flattening the union of SchemaArg's input types](https://github.com/lvauvillier/nexus-schema-plugin-prisma/blob/d7f58cf1d63e157b71cc461d9dfd3984a0f26e79/src/dmmf/transformer.ts#L95) to begin with, and the addition is that they strip out the atomic operations in case they were disabled.
Looking at the SchemaArg definition here, it seems that the [inputTypes is not being handled](https://github.com/MichalLytek/typegraphql-prisma/blob/37eb2e7fa5cc36a28d56a44fc011f541c8274c0f/src/generator/dmmf/types.ts#L107) at the moment.

To the best of my understanding, this seems to be the way to go.

**Comment by neilljordan** [comment]
For people like me who missed the setting initially, this was resolved with the addition of the _useSimpleInputs_ as documented here: https://prisma.typegraphql.com/docs/advanced/simple-inputs
