### ISSUE TITLE
noncount noun / no plural form

### ISSUE THREAD

**Issue by mwillbanks** [MichalLytek/typegraphql-prisma#327]
**Describe the Bug**
When generating out the graphql schema, noncount nouns or words that have no plural forms cause the generation to skip in generating out 2 queries (the singular and plural form) of the find unique and find many for the specific cases (well, they're generated but they're called `findUnique*` and `findMany*`).

Example equipment will not generate out a query of `equipment` (findUnique) or `equipments` (findMany).

This is inside of the code for translating the dmmf: https://github.com/MichalLytek/typegraphql-prisma/blob/main/src/generator/dmmf/transform.ts#L426

**To Reproduce**
Create a model with a non-plural form word, it will not generate out a singular findUnique or plural findMany.

```
model Equipment {
  id  String  @id @default(ccuid())
}
```

**Expected Behavior**

On a noncount noun or no plural form, append an `s` to the end of the word anyway to account for handling this or provide a configuration option to be able to provide the singular / plural form to be utilized. My thinking is the ability to provide a customized plural form might be best.

**Comment by MichalLytek** [comment]
Fixed by 80ce036, released in `v0.21.5` 🚀
