### ISSUE TITLE
Upgrade Prisma to v4.4

### ISSUE THREAD

**Issue by alecrobins** [MichalLytek/typegraphql-prisma#336]
**Is your feature request related to a problem? Please describe.**
4.4 released a ton of bug fixes including a fix that will unblock our team https://github.com/prisma/prisma/issues/14799

**Describe the solution you'd like**
Bumping the supported Prisma version from 4.3 to 4.4

**Describe alternatives you've considered**
We're unable to come up with a solution to resolve https://github.com/prisma/prisma/issues/14799 without upgrading to 4.4.

**Additional context**
Thanks so much for maintaining this library! It's a critical part of our infra :)

**Comment by MichalLytek** [comment]
`typegraphql-prisma` is constantly upgraded to support the newest Prisma release. There's no need to remind me every time about upgrading 😉 

You can try `v.4.4` on your own:
https://prisma.typegraphql.com/docs/basics/prisma-version#lifting-prisma-version-restriction

**Comment by alecrobins** [comment]
Thanks @MichalLytek 👍 I didn't know about https://prisma.typegraphql.com/docs/basics/prisma-version#lifting-prisma-version-restriction
