### ISSUE TITLE
Ability to roll back transaction when resolver enhancer throws after next()

### ISSUE THREAD

**Issue by mdesousa** [MichalLytek/typegraphql-prisma#338]
We would like to be able to roll back the prisma transaction when a resolver enhancer encounters a problem after `next()` has executed. This would be useful if validation of the result fails, or if a follow-up operation (like recording to an audit trail) fails.

For additional background, please see [prisma 155592](https://github.com/prisma/prisma/issues/15592). I was thinking about doing this in prisma... but it may be a better fit for typegraphql-prisma.
The interactive transaction feature in prisma may provide a way to implement this.

Thanks

**Comment by MichalLytek** [comment]
I'm not sure if this is a feature request or a question 🤔 
Have you tried making a middleware that is wrapping `next()` in try catch and assigning prisma transaction to `ctx.prisma`?

**Comment by mdesousa** [comment]
thanks @MichalLytek ... it was a feature request, but you are right... there is away to implement this!
so your suggestions is to do this?
```
async (action, next) => {
    const { prisma } = action.context;
    const result = await prisma.$transaction(async (prisma) => {
      action.context.prisma = prisma as PrismaClient;
      const result = await next();
      validate(result); // throws if validation fails
      return result;
    });
    action.context.prisma = prisma;
    return result;
  };
```
