### ISSUE TITLE
Use GraphQL Native `ID` type for ids

### ISSUE THREAD

**Issue by robertt** [MichalLytek/typegraphql-prisma#344]
Hey Michał - first of all, thanks for making this library! we've been using it for a new codebase at my company and it's proven excellent.

One issue we've ran into is using Relay with it, specifically complying with the [Global Object Identification](https://graphql.org/learn/global-object-identification/) spec. Something this (and many other specs) require is ids use the native `ID` type instead of just `String` (or whatever the type would be). Seeing as you have context on which Prisma fields are ids, either generating it automatically or including an option to use `ID` makes sense to me. 

Would be happy to PR this myself if needed, just making sure this is something you'd be willing/interested in it being implemented.

**Comment by MichalLytek** [comment]
I think it's just undocumented by accident:
https://github.com/MichalLytek/typegraphql-prisma/issues/26

**Comment by robertt** [comment]
Oh amazing, thanks! Not sure how I didn't find that issue. Will close!
