### ISSUE TITLE
Ability to use custom @ObjectType decorator

### ISSUE THREAD

**Issue by robertt** [MichalLytek/typegraphql-prisma#345]
It would be great if we were able to customize the generated @ObjectType decorator, or have the ability to disable automatic generation of it and apply it manually through `applyModelsEnhanceMap` (the latter is probably the preferable solution.)

Reasoning is because we need to have a Relay compliant schema, and some of our models need to implement another model we have (specifically, `Node`, which only contains an id: ID! field.) I can see this has already been discussed a bit in #18, but either way would be very nice to have this.

**Comment by robertt** [comment]
@MichalLytek would you be interested in me PRing this?

**Comment by MichalLytek** [comment]
Please describe the proposed solution first. It's better to spend 30mins on discussing than 6h on implementing incorrect solution 😉

**Comment by robertt** [comment]
agreed! i think a comment above the model definition would work best for this, i.e.
```prisma
/// @TypeGraphQL.omit(objectType: true)
model User {
  id String @id
  ...
}
```
All this comment would do is prevent `@ObjectType` from being generated on the model, and instead require it to be added later in `applyModelsEnhanceMap`. Maybe we could even throw an error if it's not added in it?

**Comment by MichalLytek** [comment]
I think `omit(objectType: true)` sounds like do not emit object type class at all for selected model 🤔 

We might need a dedicated decorator for that 🧐

**Comment by robertt** [comment]
True - I think because this is a bit more of an edge case we could be more verbose about it, i.e. `@TypeGraphQL.omitObjectTypeDecorator()`?

**Comment by robertt** [comment]
Or, maybe `/// @TypeGraphQL.omit(objectTypeDecorator: true)`?
