### ISSUE TITLE
Typegraphql-prisma: Permission denied

### ISSUE THREAD

**Issue by qlaffont** [MichalLytek/typegraphql-prisma#359]
**Describe the Bug**
Impossible to run typegraphql-prisma on github actions

**To Reproduce**
https://github.com/flexper/starter-api

**Expected Behavior**
To work 

**Logs**
https://github.com/flexper/starter-api/actions/runs/4208133736/jobs/7303791102

**Additional Context**

**Comment by MichalLytek** [comment]
Does it happen on an earlier version of `typegraphql-prisma` or it's your first try to run it on github actions?

**Comment by qlaffont** [comment]
It was working before if you check on CI history of master branch

**Comment by qlaffont** [comment]
It was working until this commit who update prisma + typegraphql + prisma-field-encryption
https://github.com/flexper/starter-api/commit/b8e3ffe97724ee697852227487d0fe603963c791

**Comment by MichalLytek** [comment]
Nothing changed for the last 1-2 year in the generator architecture / cli, so this might be related to some changes on Prisma side.
Does it also happen to other prisma generator or your prisma ones?

**Comment by qlaffont** [comment]
The very strange thing is I can't reproduce the issue on my laptop.
Maybe it's due to .npmrc changes too.

But as I see on the logs, it starts directly on typegraphql-prisma before prisma client

**Comment by qlaffont** [comment]
So I can't answer your question :/

**Comment by MichalLytek** [comment]
I mean that maybe Prisma has changed the way of invoking third-party generators, so you should report the issue on their repo in that case.

**Comment by qlaffont** [comment]
fixed issue with pnpm https://github.com/pnpm/pnpm/issues/5890
