### ISSUE TITLE
property '_all' is missing in type '{ ... }'

### ISSUE THREAD

**Issue by mdesousa** [MichalLytek/typegraphql-prisma#361]
After upgrading to version 0.24.0 I am seeing this error with existing `ResolversEnhanceMap` objects that I had defined

**To Reproduce**
Upgrade to version 0.24.0 and build a project that had enhancers implemented

**Expected Behavior**
Project should build successfully

**Additional Context**
I see `_all` is a new feature added in 0.24... but the property should probably be optional?

**Comment by MichalLytek** [comment]
Fixed in 95149e0 🔒 

Thanks for reporting 🙏
