### ISSUE TITLE
Relation fields not available in qieries' selection

### ISSUE THREAD

**Issue by lukigarazus** [MichalLytek/typegraphql-prisma#37]
I have a simple app with the following Prisma schema:

```
model TodoViewTodo {
  id          Int      @id @default(autoincrement())
  todo        Int
  todoView    Int
  placeholder String?
  Todo        Todo     @relation(fields: [todo], references: [id])
  TodoView    TodoView @relation(fields: [todoView], references: [id])
}

model Todo {
  id           Int            @id @default(autoincrement())
  text         String
  done         Boolean?
  user         Int
  User         User           @relation(fields: [user], references: [id])
  TodoViewTodo TodoViewTodo[]
}

model TodoView {
  id           Int            @id @default(autoincrement())
  label        String
  order        String?
  color        String
  TodoViewTodo TodoViewTodo[]
}
```

There should be a way to get those relational fields, like:
```
query {
    todoViews {
      id
      TodoViewTodo {
        id
      }
    }
}
```
It is possible to filter the result using relational fields:
```
query {
  todoViews(
    where: {
      TodoViewTodo: { every: { Todo: { is: { done: { equals: true } } } } }
    }
  ) {
    id
  }
}
```
so I think it would be only consistent if it was possible to select those fields too.

**Comment by MichalLytek** [comment]
> However, if you also want to have relations like User -> posts emitted in schema, you need to import also the relations resolvers and register them in your buildSchema call:

```ts
import {
  User,
  UserRelationsResolver,
  UserCrudResolver,
} from "@generated/type-graphql";

const schema = await buildSchema({
  resolvers: [CustomUserResolver, UserRelationsResolver, UserCrudResolver],
  validate: false,
});
```

**Comment by MichalLytek** [comment]
Sorry, I don't follow what the request is about and what do you expect.

You have two base models `Todo` and `TodoView` which have many-to-many relation using `TodoViewTodo` model.
Let's translate that to a more understandable case with `Post` and `Category` models, where post can have multiple categories, so single categories can contain multiple posts.

Now you propose that "there should be a way to get those relational fields".
So you are talking about:
```graphql
query {
  posts {
    title
    content
    categories {
      name
    }
  }
}
```

If yes, this is possible right now by default, you just need to import generated `resolvers` array or explicitly import Crud and Relation resolvers manually.
