### ISSUE TITLE
Update prisma version 2.12.0

### ISSUE THREAD

**Issue by thakkaryash94** [MichalLytek/typegraphql-prisma#38]
Not an issue but Prisma version 2.12.0 is released with few changes.

The major change I think is **Move most types under the Prisma namespace**.

[https://github.com/prisma/prisma/releases/tag/2.12.0](https://github.com/prisma/prisma/releases/tag/2.12.0)

**Comment by MichalLytek** [comment]
Thanks for the report. I'm aware of that as I'm in direct contact with Prisma team, there's no need to remember about the upgrade 😉 

The changes were done last week. Now I need to update deps, docs and double check everything before releasing new version.

![image](https://user-images.githubusercontent.com/10618781/100349942-731b8180-2fe9-11eb-9601-27ace5fd2a91.png)

**Comment by thakkaryash94** [comment]
I saw the commit. Just couldn't hold myself so asked because I have no idea what is pending that I can help with. So asked. No problem ☺️
