### ISSUE TITLE
Should omit hide fields from d.ts files?

### ISSUE THREAD

**Issue by shawnjones253** [MichalLytek/typegraphql-prisma#388]
**Describe the Bug**
`Typegraphql.omit(output: true)` does not prevent a field from showing up in the model's `d.ts` file, although it does prevent the field from being defined in the corresponding `.js` file.

**To Reproduce**
```
// schema.prisma
model MyModel {
  id                      String       @id @default(uuid())
  /// @TypeGraphQL.omit(output: true)
  hidden             String
}
```

```
// @generated/type-graphql/models/MyModel.d.ts
export declare class MyModel {
    id: string;
    hidden: string;
}
```

```
// @generated/type-graphql/models/MyModel.js
let MyModel = class MyModel {
};
tslib_1.__decorate([
    TypeGraphQL.Field(_type => String, {
        nullable: false
    }),
    tslib_1.__metadata("design:type", String)
], MyModel.prototype, "id", void 0);
MyModel = tslib_1.__decorate([
    TypeGraphQL.ObjectType("MyModel", {
        isAbstract: true
    })
], MyModel);
exports.MyModel = MyModel;
```

**Expected Behavior**
Should `hidden` be missing from `MyModel.d.ts` like it is from `MyModel.js`?

**Environment (please complete the following information):**

- OS: Mac Ventura 13.3.1
- Node 16.20.0
- `typegraphql-prisma` version 0.24.7
- Prisma version 4.13.0
- TypeScript version 4.8.4

**Comment by MichalLytek** [comment]
No. `@TypeGraphQL.omit`does not affect TS side of the type. The field still exists in runtime, is returned from Prisma Client calls and can be accessed by the field resolvers. 

`@TypeGraphQL.omit` only acts as not placing the `@Field` decorator on the class field.
