### ISSUE TITLE
How to write tests on resolvers

### ISSUE THREAD

**Issue by SheaBelsky** [MichalLytek/typegraphql-prisma#39]
I'd like to write unit tests for resolvers in an app that uses this package. I've been following the guidance of this issue on writing tests:

https://github.com/MichalLytek/type-graphql/issues/231#issuecomment-455799974

Does this model also work in an environment with Prisma? What extra steps are necessary to be able to test _custom_ resolvers, if any? Would they be the same as if we were testing TypeGraphQL resolvers without Prisma?

**Comment by MichalLytek** [comment]
You shouldn't need to write tests for the generated resolvers.
Custom resolvers are just like standard TypeGraphQL resolvers without Prisma.
You don't need any special testing approach.

You should focus on integration tests which are the same as with any other graphql framework.
Just build the GraphQL schema object and execute your test queries against it.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
