### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined when running prisma:generate

### ISSUE THREAD

**Issue by jsefiani** [MichalLytek/typegraphql-prisma#4]
Whenever I run prisma generate, I get the following error: TypeError: Cannot read property 'filter' of undefined

This error started occurring after upgrading to typegraphql-prisma to v0.8.0

![image](https://user-images.githubusercontent.com/40734088/95108256-56767200-073b-11eb-8c6c-274de242d971.png)

**Comment by MichalLytek** [comment]
I'm tired of telling you the same thing again and again, so please read the readme and install supported prisma version.

**Comment by jsefiani** [comment]
That's really impolite Michal.

**Comment by jsefiani** [comment]
Nevertheless thank you for reminding me a second time

**Comment by MichalLytek** [comment]
The next release will check the prisma version in runtime and throw the red banner in the console to remind about reading the readme and peer dependency warnings 😉

**Comment by jsefiani** [comment]
That would be really helpful because it's human to forget and I really forgot to check the version of Prisma.

**Comment by MichalLytek** [comment]
Implemented in 62dbf047
