### ISSUE TITLE
Error: Unrecognized scalar type: Bytes

### ISSUE THREAD

**Issue by rossinicolas** [MichalLytek/typegraphql-prisma#40]
Hello, i'm using the Prisma/cli and prisma/client version 2.12.1. i'm using these because i hava Bytea fields in psql and the introspection convert it to Bytes.
This scalar type isn't an option on helpers.js file.
Could you tell me what can i fix it.
Thanks in advance.

**Comment by MichalLytek** [comment]
> Native database types in the Prisma schema (Preview)

Preview features are a subject to change thus `typegraphql-prisma` might not always support them unless explicitly specified in the release notes.

I will check how complicated is adding support for that preview feature.

**Comment by rossinicolas** [comment]
could be a Buffer type?

**Comment by MichalLytek** [comment]
The mapping is well described:
https://www.prisma.io/docs/concepts/components/preview-features/native-types#working-with-new-types-in-prisma-client

![opera_TQMzrcSP5p](https://user-images.githubusercontent.com/10618781/100989784-7c5c9f00-3551-11eb-8168-1c9061b050fc.png)


However, the feature is not ready:

> Prisma Migrate does not yet support native database type attributes. 

So it breaks my workflow of this package, so I can't add support for it yet. We have to wait for the next preview release or maybe even stable one.

**Comment by rossinicolas** [comment]
That's ok, i understood but i think that could be usefull have the Bytes field type to can use the features like prisma.create or prisma.findUnique to datatables that had Bytea file and are present in the introspect data model independentry of we can't use migrate at moment.

**Comment by MichalLytek** [comment]
Closing via `v0.11.0` 🔒 
https://github.com/MichalLytek/typegraphql-prisma/releases/tag/v0.11.0
