### ISSUE TITLE
Prisma 5

### ISSUE THREAD

**Issue by vieirai** [MichalLytek/typegraphql-prisma#401]
Prisma has recently released version 5+: https://www.prisma.io/blog/prisma-5-f66prwkjx72s

Will we have support for this soon?

**Comment by vieirai** [comment]
Hey @MichalLytek , I saw you labelled this as `good first issue`, would you be open for me raising a PR to add Prisma 5 support?

What I want to avoid is working on the PR and then having it sit in the `Pull requests` tab unmerged.

**Comment by MichalLytek** [comment]
It's farily easy process, assuming there's no breaking changes.
All you need to do is bump prisma versions (all packages) in root package json as well as experiments folders, install all deps, run prisma generate, check for diff in generated files, run tests to see all works, bump version in peer deps, bump version in installation docs and that's it!

**Comment by ramiel** [comment]
Hello. I think this change https://www.prisma.io/docs/guides/upgrade-guides/upgrading-versions/upgrading-to-prisma-5#using-private-apis-for-a-specific-runtime makes it difficult to upgrade to version 5 since things like `DMMF` are not exposed anymore. You need a deeper knowledge to make this work.

**Comment by qlaffont** [comment]
Maybe we can try to setup a github workflow to handle prisma update.
- Use renovatebot to automatically detect prisma changes
- Run on renovatebot PR tests
- If success, merge PR on master
- If merge PR on master, increase version and publish on master. 

I have already done it on some libraries and it works perfectly. If needed to implement this : you can found a good example here : https://github.com/flexper/paginate-prisma/blob/main/.github/workflows/publish.yml

**Comment by MichalLytek** [comment]
Wasn't so hard, closing by 66d3b2f 🔒
