### ISSUE TITLE
[Prisma 5] Impossible to use emitOnly properties

### ISSUE THREAD

**Issue by qlaffont** [MichalLytek/typegraphql-prisma#405]
**Describe the Bug**
When I use the property : emitOnly it failed on generation

**To Reproduce**
- Use property emitOnly on schema.prisma
- Generate prisma client

**Expected Behavior**
To works

**Logs**
https://github.com/flexper/starter-api/actions/runs/5604765614/job/15184208755?pr=329

**Environment (please complete the following information):**

- OS: Github Action Ubuntu
- Node 18.X
- `typegraphql-prisma` version [e.g. 0.11.1] : 0.27.0
- Prisma version [e.g. 2.18.0] : 5.0.0
- TypeScript version (e.g. 4.2.2) : 5.1.6

**Additional Context**
ref https://github.com/flexper/starter-api/pull/329

**Comment by MichalLytek** [comment]
Have you changed your syntax to array-based?
https://prisma.typegraphql.com/docs/advanced/emit-blocks

**Comment by qlaffont** [comment]
Thanks I didn't see the syntax have been changed !
