### ISSUE TITLE
Potential memory leak in generation with `@types/lodash`

### ISSUE THREAD

**Issue by dahaupt** [MichalLytek/typegraphql-prisma#414]
**Describe the Bug**
The generation with `npx prisma generate` hangs and results in a fatal error.

**To Reproduce**
The issue started to occur after installing `graphql-shield@7.6.5` which also installs `@types/lodash@4.14.197`:
```
$ npm ls @types/lodash
my-project
└─┬ graphql-shield@7.6.5
  └─┬ yup@0.32.11
    └── @types/lodash@4.14.197
```

**Expected Behavior**
Generation should not be affected by installation of `graphql-shield` / `@types/lodash`. 

**Logs**
```
$ npx prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: 
✔ Generated Prisma Client (4.15.0 | library) to ./node_modules/@prisma/client in 54ms

Generator "typegraphql-prisma" failed:

<--- Last few GCs --->
[104011:0x680b1f0]    68084 ms: Mark-sweep (reduce) 2041.6 (2083.4) -> 2040.5 (2083.6) MB, 646.4 / 0.0 ms  (average mu = 0.222, current mu = 0.130) allocation failure; scavenge might not succeed
[104011:0x680b1f0]    68777 ms: Mark-sweep (reduce) 2041.5 (2083.6) -> 2040.8 (2084.1) MB, 663.1 / 0.0 ms  (average mu = 0.141, current mu = 0.043) allocation failure; scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb83f50 node::Abort() [node]
 2: 0xa94834  [node]
 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf42265  [node]
 6: 0xf5474d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xf2ee4e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xf30217 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xf113ea v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x12d674f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x17035b9  [node]
Aborted (core dumped)
```

**Environment:**

- OS: Ubuntu 23.04
- Node: 18.17.1
- `typegraphql-prisma`: 0.26.0
- Prisma: 4.15.0
- TypeScript: 5.1.3

**Additional Context**
I have traced the issue to the file `node_modules/@types/lodash/common/seq.d.ts`. The generation works again without any issues after removing this specific file. I also noticed, that the generation is faster after removing `@types/lodash` completely (~ 8 -> 3 seconds for one defined simple model).

**Comment by dahaupt** [comment]
Possibly related to #382

**Comment by MichalLytek** [comment]
Can you play with `skipLibCheck: true,` in `src/generator/generate-code.ts#L55`?

**Comment by dahaupt** [comment]
@MichalLytek Thanks for your fast reply. The issue is fixed when I add `skipLibCheck: true` to the `baseCompilerOptions` object. Can I set this also in my `schema.prisma` as a temporary workaround?

**Comment by robertt** [comment]
Is there any reason why `skipLibCheck` is not enabled by default? Adding it takes our gen times on an M1 Pro macbook from 90s -> 30s (Prisma 5.5.) In GitHub actions the runner runs out of memory. @dahaupt could you share your patch-package?

@MichalLytek on a similar note, we (https://github.com/withprimer) are interested in sponsoring work to speed up gen times here - lmk if interested.

**Comment by MichalLytek** [comment]
`skipLibCheck` enabled in 9c87cdb 🔒
