### ISSUE TITLE
Code is Generated Incorrectly for `0.27.0`

### ISSUE THREAD

**Issue by SomeUserNameReally** [MichalLytek/typegraphql-prisma#415]
**Describe the Bug**
Reference https://github.com/prisma/prisma/issues/18342#issuecomment-1476980186

Running

```sh
npx prisma generate
```
or equivalent incorrectly generates `prisma/generated/type-graphql/helpers.ts`.

The line

```ts
const [[key, { value }]] = Object.entries(argument);
```
at `prisma/generated/type-graphql/helpers.ts` is structured unexpectedly.

**To Reproduce**
Generate under these conditions with comment directives, like `/// @onDelete(CASCADE)`, set on `schema.prisma`.

**Expected Behavior**
Everything generates and runs without errors.

**Logs**
Please ask, I will provide as necessary.

**Environment (please complete the following information):**

- OS: Manjaro (kernel 6.4.9-1, kde 5.27.7)
- Node 16.19.1
- `typegraphql-prisma` version 0.27.0
- Prisma version 5.11.1
- TypeScript version 4.3.2
-  Openssl Version 3.1.x

**Comment by MichalLytek** [comment]
> with comment directives, like /// @onDelete(CASCADE), set on schema.prisma.

I'm not sure what issue do you report. `@onDelete` is a Prisma attribute that should be placed without docs.
"Comment directives" are only used for `@TypeGraphQL` ones.

**Comment by SomeUserNameReally** [comment]
@MichalLytek The main issue here is that we get incorrect code generation on running `prisma generate`. I looked at the source and I think this may be a bug with how TS types are generated. Not sure. Either way, I don't think comment directives or Prisma attributes have anything to do with it. Sorry if I wasn't clear on this before.

**Comment by MichalLytek** [comment]
Unable to reproduce 🔒
