### ISSUE TITLE
Naming a model "Function" in the schema.prisma crashes the generator

### ISSUE THREAD

**Issue by willcbelcher** [MichalLytek/typegraphql-prisma#419]
**Describe the Bug**
Naming a model "Function" in the schema.prisma crashes the generator

**To Reproduce**
Create a simple schema and name the model "Function". Then run prisma generate. When trying to run the server, it will crash with typescript/js errors.

**Expected Behavior**
The generator works and correctly provides auto-generated CRUD resolvers

**Logs**
N/A

**Environment (please complete the following information):**

- OS: Linux, Pop-OS 22.04 LTS
- Node (e.g. 15.8.0): node v 18.17.1, yarn version 1.22
- `typegraphql-prisma` version 0.27.0
- Prisma version [e.g. 2.18.0] 4.16.2
- TypeScript version (e.g. 4.2.2) 5.1.6

**Additional Context**
Not sure if this is a bug, or if it isn't really worth taking the time to fix, but the model name "Function" is essentially forbidden because of this bug. If it is not in scope, please feel free to close this issue.

**Comment by MichalLytek** [comment]
I think ECMAScript rules forbid using this name as the name for the class, so we would have a ton of workaround so it might be simpler just to rename your model:
https://prisma.typegraphql.com/docs/advanced/renaming-model
