### ISSUE TITLE
Use within the web browser completely? a question, not an issue

### ISSUE THREAD

**Issue by PhilAndrew** [MichalLytek/typegraphql-prisma#44]
Hello, this is a question, not an issue.

I would like to use all of this, typeorm and this project all within the browser, without a nodejs server.

Having established that I can use typeorm from within the browser with the database within the browser and run an example code which does that, then I want to use this tool typegraphql-prisma to generate the files and then from prisma and do graphql queries.

I've tried to embed ApolloServer within the web browser using webpack but failed to do so, it seems to use too many nodejs dependencies which will not work in the browser via webpack.

So the question is, can you give any advice how I could go about getting all of this to work within the web browser? Being able to store state within the database within the web browser and applying GraphQL queries on that is my goal.

could I run a graphql query using typegraphql in the browser using the outputs of this prisma typegraphql project? I mean using the files outputted from the prisma

**Comment by MichalLytek** [comment]
Sorry, but what is the purpose of creating http server in the browser? 😅 

You have db in browser, you have typeorm, so just use the typeorm entities/repositories directly in your client code.

HTTP and GraphQL is for communicating your client (browser) app with the backend (server).

**Comment by PhilAndrew** [comment]
You have some misunderstanding of what I wrote. It's not a http server in the browser, I didn't mention http server.

It's a graphql interface to the database in memory inside the web browser. The database is loaded in memory, I wish to provide a graphql interface to that database loaded in memory so that my code is without a server. If and when I want to provide a server then I would still have the same graphql interface.

If as you proposed I used typeorm directly in my client code to this database then I would need to refactor my code to use two different interfaces to the database if I want to switch between graphql on the server and graphql interface to the in memory database in the client web browser which would be unattractive.

I don't understand what you wrote "All you can do is to genereate a GraphQL schema in the browser and use that directly, without apollo server (or with the in-memory apollo test client.".

**Comment by MichalLytek** [comment]
`typegraphql-prisma` only generates TypeGraphQL code, so if you ask about running GraphQL schema in the browser, please search about running `graphql-js` schema in the browser or create an issue in main typegraphql repo if you fail to mock node dependencies in webpack to make it run.

If you ask about running Prisma in the browser, again - wrong repo, go ask on Prisma repository about that.
I think it's not possible as Prisma is a Rust binary with only JS client. TypeORM is pure JS ORM so it can work in browser.

> I don't understand what you wrote "All you can do is to genereate a GraphQL schema in the browser and use that directly, without apollo server (or with the in-memory apollo test client.".

https://www.apollographql.com/docs/link/links/schema/

```ts
import { SchemaLink } from 'apollo-link-schema';
import { buildSchema } from 'type-graphql';

const schema = await buildSchema({ resolvers });

const graphqlClient = new ApolloClient({
  cache: new InMemoryCache(),
  link: new SchemaLink({ schema })
});
```
