### ISSUE TITLE
update disconnect fails when disconnecting multiple items

### ISSUE THREAD

**Issue by mahsohn** [MichalLytek/typegraphql-prisma#444]
When I try to disconnect multiple ids on an update query, prisma throws an error. The schema generated allows for the disconnect to be a ModelWhereInput but prisma is expecting a ModelWhereUniqueInput so I can only disconnect one per query.

**Comment by MichalLytek** [comment]
This should not happen as input types are generated based on Prisma DMMF, which is based on generated Prisma Client.
