### ISSUE TITLE
Improve applying custom decorators

### ISSUE THREAD

**Issue by arxenix** [MichalLytek/typegraphql-prisma#45]
In the config passed to `applyResolversEnhanceMap`, is there any way to pass in "wildcard" decorators that are applied to all fields of the type?

Additionally, a way to specify a "default" set of decorators that get applied to all fields would be nice.

Similar to how graphql-shield does it: https://github.com/maticzav/graphql-shield#per-type-wildcard-rule

**Comment by MichalLytek** [comment]
Good idea! It should be fairly easy to implement 😉

**Comment by MichalLytek** [comment]
@arxenix [`v0.12.0`](https://github.com/MichalLytek/typegraphql-prisma/releases/tag/v0.12.0) now allows to specify `_all` key which applies the decorators to all fields of the type 🎉 

Any feedback is highly welcome 😉 Maybe you have some other cool improvement ideas?
