### ISSUE TITLE
Error message: ApolloServer context parameter

### ISSUE THREAD

**Issue by DakotaLarson** [MichalLytek/typegraphql-prisma#46]
When prisma is not returned as part of the context callback in the ApolloServer constructor, a generic "cannot get x of type undefined" is returned whenever a graphql query is run. This is documented in the README, however, a more helpful error message could go a long way here. I lost a fair amount of time debugging this issue until I found the relevant documentation.

 Essentially, check if prisma exists on the context object, and if it doesn't, throw a more helpful error.

**Comment by MichalLytek** [comment]
Closing via 4311dce 🔒
