### ISSUE TITLE
How to create multiple tags for a article? / many to many / prisma 2

### ISSUE THREAD

**Issue by ulziibadrakh-p** [MichalLytek/typegraphql-prisma#47]
For example
article -> article_tag -> tag

```
article(where:{id:id}) {
  id
  title
  text
  tags(data:{[
    {title:1},
    {title:2},
    {title:3},
  ]}) {
      id
      title
  }
}
```

**Comment by MichalLytek** [comment]
Please show your prisma schema (the part related to the request) or create a reproducible minimal code example repo with instructions to reproduce the issue.

**Comment by ulziibadrakh-p** [comment]
I solved it by just nested gql query
