### ISSUE TITLE
Many to Many Relations resolver seems to confuse field order

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/typegraphql-prisma#49]
I have this model (simplified version):

```prisma
model User {
  id                String      @id @default(cuid())
  name              String
  memberOfProjects  UsersOnProjects[]
  ownsProjects      Project[]
}

model Project {
  id            String      @id @default(cuid())
  owner         User        @relation(fields: [ownerId], references: [id])
  ownerId       String
  members       UsersOnProjects[]
}

model UsersOnProjects {
  project       Project     @relation(fields: [projectId], references: [id])
  projectId     String
  user          User        @relation(fields: [userId], references: [id])
  userId        String
  createdAt     DateTime    @default(now())

  @@id([userId, projectId])
}
```

After the typegraphql generation I have this relations resolver:

```ts
import * as TypeGraphQL from "type-graphql";
import { Project } from "../../../models/Project";
import { User } from "../../../models/User";
import { UsersOnProjects } from "../../../models/UsersOnProjects";

@TypeGraphQL.Resolver(_of => UsersOnProjects)
export class UsersOnProjectsRelationsResolver {
  @TypeGraphQL.FieldResolver(_type => Project, {
    nullable: false
  })
  async project(@TypeGraphQL.Root() usersOnProjects: UsersOnProjects, @TypeGraphQL.Ctx() ctx: any): Promise<Project> {
    return ctx.prisma.usersOnProjects.findUnique({
      where: {
        projectId_userId: {
          projectId: usersOnProjects.projectId,
          userId: usersOnProjects.userId,
        },
      },
    }).project({});
  }

  @TypeGraphQL.FieldResolver(_type => User, {
    nullable: false
  })
  async user(@TypeGraphQL.Root() usersOnProjects: UsersOnProjects, @TypeGraphQL.Ctx() ctx: any): Promise<User> {
    return ctx.prisma.usersOnProjects.findUnique({
      where: {
        projectId_userId: {
          projectId: usersOnProjects.projectId,
          userId: usersOnProjects.userId,
        },
      },
    }).user({});
  }
}
```

Then I am trying to query this:
```gql
query project($id: String!) {
    project(where: {id: $id}) {
        id
        createdAt
        members(where: {projectId: {equals: $id}}) {
            user {
                name
                id
            }
        }
        content
    }
}
```

But apollo returns an error:

```
{
  where: {
    projectId_userId: {
    ~~~~~~~~~~~~~~~~
      projectId: 'somerandomid',
      userId: 'anotherrandomid'
    }
  },
  select: {
    user: {}
  }
}

Unknown arg `projectId_userId` in where.projectId_userId for type UsersOnProjectsWhereUniqueInput. Did you mean `userId_projectId`? Available args:
type UsersOnProjectsWhereUniqueInput {
  userId_projectId?: UsersOnProjectsUserIdProjectIdCompoundUniqueInput
}
```

Changing the queried field in the generated relations resolver accordingly to `userId_projectId` instead of `projectId_userId` fixes the issue, but of course after regeneration the error pops up again.

I am not quite sure why it has to be a specific order, but I guess the generator has to be fixed to swap the order of the fields in the relation.

**Comment by MichalLytek** [comment]
If `projectId_userId` changes to `userId_projectId` after regeneration, then it's a Prisma issue with not stable keys in client. If you're sure about that, please report that in the upstream prisma repo.

**Comment by JohannesKlauss** [comment]
But it doesn't change after regeneration. The prisma key is stable (it keeps being `userId_projectId` when I generate the client from the model), but the generated GraphQL resolver is always exactly the other way round.

**Comment by MichalLytek** [comment]
`typegraphql-prisma` only translates Prisma's DMMF into TypeGraphQL classes. It doesn't generates the keys or names, so it must be an issue with the DMMF.

I will take a look at your example and try to reproduce it to report the issue upstream in Prisma repo.

**Comment by JohannesKlauss** [comment]
ah ok. Didn't know that. Yeah, then it is probably a prisma related issue. Weird.

**Comment by MichalLytek** [comment]
@JohannesKlauss It ended up as my mistake and the change fix was fairly easy 😅 

![image](https://user-images.githubusercontent.com/10618781/106606531-88b9a400-6562-11eb-9c47-44e491790c4a.png)

I will add a test for this and will release it soon 😉

**Comment by MichalLytek** [comment]
Closing via f1a3b3a 🔒

**Comment by JohannesKlauss** [comment]
Thank you for looking into it and thank your for the fix.
