### ISSUE TITLE
Authorization of generated relation resolvers

### ISSUE THREAD

**Issue by joseaquino** [MichalLytek/typegraphql-prisma#50]
I've been searching and trying different approaches but can't find a way to apply authorization decorator to a relation resolver in a list operations, for example if I have the following schema:

```prisma
model Book {
  id       Int
  author   Author @relation(fields: [authorId], references: [id])
  authorId Int
}

model Author {
  id    Int
  books Book[]
}
```

`typegraphql-prisma` would then generate the `resolvers/crud/Book/BookCrudResolver.ts` file which would contain a list resolver as follows:
```ts
@TypeGraphQL.Query(_returns => [Book], {
  nullable: false
})
async books(@TypeGraphQL.Ctx() ctx: any, @TypeGraphQL.Args() args: FindManyBookArgs): Promise<Book[]> {
  return ctx.prisma.book.findMany(args);
}
```
And a single entry resolver like this:
```ts
@TypeGraphQL.Query(_returns => Book, {
  nullable: true
})
async book(@TypeGraphQL.Ctx() ctx: any, @TypeGraphQL.Args() args: FindUniqueBookArgs): Promise<Book | null> {
  return ctx.prisma.book.findUnique(args);
}
```
And for the relationship with the `User` there would be another file at `resolvers/relations/Book/BookRelationsResolver.ts` which would contain a field resolver for the stablished one-to-many relationship with `User` like this:
```ts
@TypeGraphQL.FieldResolver(_type => Author, {
  nullable: false
})
async author(@TypeGraphQL.Root() book: Book, @TypeGraphQL.Ctx() ctx: any): Promise<Author> {
  return ctx.prisma.book.findUnique({
    where: {
      id: book.id,
    },
  }).author({});
}
```
Now for the authorization part I have tried the following decorator mapping:
```ts
const modelsEnhanceMap: ModelsEnhanceMap = {
  Book: {
    fields: {
      author: [Authorized()],
    }
  }
}
```
And it works fine for the single entry resolver `book` but it doesn't work for the list resolver `books`. 

My questions is how to also apply the authorization to the listing? I suspect this might be a bug as it works in one side but not the other.

Using latest versions of `typegraphql`, `typegraphql-prisma` and `prisma`

**Comment by MichalLytek** [comment]
> My questions is how to also apply the authorization to the listing?

Read the docs and use `ResolversEnhanceMap`:
https://github.com/MichalLytek/typegraphql-prisma/blob/main/Readme.md#additional-decorators-for-prisma-schema-resolvers

**Comment by joseaquino** [comment]
Thanks for the quick response @MichalLytek, I've tried that and it only allows applying the authorization to the root resolver, in my example would be to the `books` resolver but what I want to achieve is to apply the authorization to the relation not the root. 

So to summarize it I want books to be public but the related author be private.

**Comment by MichalLytek** [comment]
Relation resolvers are not yet covered with this feature, as well as input types. You just need to wait for finalizing the #21.

**Comment by chriszrc** [comment]
@MichalLytek can you confirm whether adding @Middleware or @Authorized should run on mutations to relation resolvers that are enhanced in this way?
