### ISSUE TITLE
How to keep my custom resolver codes instead overwrite when regenerate?

### ISSUE THREAD

**Issue by ulziibadrakh-p** [MichalLytek/typegraphql-prisma#53]
For example: I wrote custom subscription method in a UserCrudResolver.

**Comment by MichalLytek** [comment]
Custom methods only in custom resolvers in a separate files. Typegraphql merges all the resolvers, so no need to add something to the generated one.

**Comment by MichalLytek** [comment]
Next time please ask on gitter - GitHub issues is not a helpdesk, it's for bug reports and feature requests.
