### ISSUE TITLE
NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system.

### ISSUE THREAD

**Issue by WilcoBreedt** [MichalLytek/typegraphql-prisma#58]
I had the following issue the whole time while trying to add inline args using the `@Arg('param') param: string` decorator. Turns out you just need to ensure that your bundler/compiler is aware of the typescript config flag `"emitDecoratorMetadata": true`

Incase you are using parceljs as a bundler, just add an tsconfig.json file in your root folder and ensure the file contains 
```js
{
  "compilerOptions": {
       "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
   }
}
```

**Comment by WilcoBreedt** [comment]
Just wanted to have this here as a reference in case anyone else struggles with the same issue as it is a simple issue that I ran into but could not google easily. Hope this helps.

**Comment by germanamz** [comment]
For what its worth and prosperity...

If you're using `tsx` it doesn't support `"emitDecoratorMetadata"` because its base on `esbuild`.
