### ISSUE TITLE
n + 1 issue

### ISSUE THREAD

**Issue by omerman** [MichalLytek/typegraphql-prisma#59]
Hello,
First of all great work on the fantastic plugin, thank you!

I wanted to check with you guys regarding n+1 issue & DataLoader mechanism.

I opened a repo https://github.com/omerman/prisma-type-graphql-n1 that has typegraphql & prisma installed.
All you need to do is modify your .env to match a postgres db, and hit `yarn dev`.

When adding multiple Posts & Comments (two Posts and a single Comment per Post will be enough) and running this basic query ->

```graphql
  posts {
    id
    comments {
      id
      info
    }
  }
```
 You'll quickly notice that the number of queries logged grow for each Post added. I believe this should not happen.. 
I think it would be best if the typegraphql generated crud methods leverage prisma2 mechanism of the implemented DataLoader.

Looking forward for your response

**Comment by MichalLytek** [comment]
Prisma has a built-in dataloader so there's no need for resolving the relations using custom, manual dataloader.

**Comment by MichalLytek** [comment]
To not leave this issue without comments, I've also run a simple query on my experimental project (`/experiments` on repo):

```graphql
query {
  clients {
    firstName
    clientPosts {
      title
    }
  }
}
```

And here are the sql logs:
```
prisma:query SELECT "public"."User"."id", "public"."User"."email", "public"."User"."name", "public"."User"."age", "public"."User"."balance", "public"."User"."amount", "public"."User"."role" FROM "public"."User" WHERE 1=1 OFFSET $1
prisma:query SELECT "public"."User"."id" FROM "public"."User" WHERE "public"."User"."id" IN ($1,$2,$3) OFFSET $4
prisma:query SELECT "public"."post"."uuid", "public"."post"."createdAt", "public"."post"."updatedAt", "public"."post"."published", "public"."post"."title", "public"."post"."subtitle", "public"."post"."content", "public"."post"."authorId", "public"."post"."editorId", "public"."post"."kind", "public"."post"."metadata" FROM "public"."post" WHERE "public"."post"."authorId" IN ($1,$2,$3) OFFSET $4
```
So as you can see, the relation is fetched without N+1 issue, it's batching the calls and making single query `FROM "public"."post" WHERE "public"."post"."authorId" IN ($1,$2,$3)`.

So please try to investigate what is different in your project/repo that makes dataloader not working 😉

**Comment by omerman** [comment]
@MichalLytek thank you for your response! 
I found out that version 2.15+ of prisma has the issue I described with batching. When downgraded to 2.14 the batching worked as expected. So its all good :) I guess Prisma guys fixed it by now(I saw an open issue at the time)
