### ISSUE TITLE
Problems getting the playground running with Nest.js

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/typegraphql-prisma#6]
I am trying to set up this package together with the nest-js package using a more modular approach than the provided example:

```ts
/// app.module.ts
interface Context {
  prisma: PrismaClient;
}

const prisma = new PrismaClient();

@Module({
  imports: [
    TypeGraphQLModule.forRoot({
      validate: false,
      dateScalarMode: "timestamp",
      playground: true,
      introspection: true,
      path: "/",
      emitSchemaFile: true,
      context: (): Context => ({ prisma })
    })
  ],
  controllers: [AppController],
  providers: [
    // Models
    User,
    Project,
    // Relations
    UserRelationsResolver,
    ProjectRelationsResolver,
    // Crud
    UserCrudResolver,
    ProjectCrudResolver,
    // Custom
  ]
})
export class AppModule {
}
```

```ts
// main.ts
async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
  await app.listen(4000);
}

bootstrap();
```

Everything starts up fine and the graphql endpoint works as expected, but opening `localhost:4000` in the browser doesn't open the playground. Is there something missing?

**Comment by MichalLytek** [comment]
I had the same issue in [the example](https://github.com/MichalLytek/typegraphql-prisma/tree/main/examples/3-nest-js) and I've end up with using Electron app "GraphQL Playground". 

Looks like there might be an issue with passing options to NestJS `GraphQLModule` or a bug in nest graphql module itself. Gonna check this soon 😉

**Comment by JohannesKlauss** [comment]
Thanks for pointing to the electron app. Works great out of the box.
Btw. thank you for all your work on those packages, it makes working with otherwise complex and redundant setups a breeze.

**Comment by MichalLytek** [comment]
Ok, I've investigated and it's and `NestFastifyApplication` issue. Even official sample no 23 on Nest repo suffers on this issue.

May I ask you to report the issue on Nest GitHub repository?
I'll leave this issue opened until it's fixed on upstream and I can update the deps in examples 😉

**Comment by JohannesKlauss** [comment]
oh, thx for checking out. I'll leave an issue there

**Comment by JohannesKlauss** [comment]
Hmh... I checked it also, running sample 23 and opening `localhost:3000/graphql` show the playground for me.

**Comment by MichalLytek** [comment]
@JohannesKlauss 
> works in standard setup and fails if you do like in your bootstrap example

You need to use fastify in the nest example to make it fail

**Comment by JohannesKlauss** [comment]
Ah sure, opened an issue here: https://github.com/nestjs/nest/issues/5544

**Comment by JohannesKlauss** [comment]
It's an issue (I already suspected that) with the apollo fastify package: https://github.com/apollographql/apollo-server/issues/4463

**Comment by MichalLytek** [comment]
@JohannesKlauss Thanks for the report!

So closing for a housekeeping purposes 🔒
Updating the deps after releasing should fix the problem.
