### ISSUE TITLE
Error message: xxx.default is not a function

### ISSUE THREAD

**Issue by HaeSe0ng** [MichalLytek/typegraphql-prisma#60]
![image](https://user-images.githubusercontent.com/14370645/108312300-d50b1200-71f9-11eb-9b0c-9086929b9003.png)

When I use aggregation query, this message comes out. I think this is because `esModuleInterop: true` option is not included in `src/generator/generate-code.ts#L49`.

**Comment by MichalLytek** [comment]
Closing via 14c130cc 🔒
