### ISSUE TITLE
Generated resolvers break with TypeDI > 0.8.0

### ISSUE THREAD

**Issue by EirikFA** [MichalLytek/typegraphql-prisma#63]
A change was introduced in TypeDI 0.9.0 that requires the `@Service` decorator for classes (see [this comment](https://github.com/typestack/routing-controllers/issues/642#issuecomment-758821736)). Using `typegraphql-prisma` with TypeDI > 0.8.0 results in an error something like the below when running queries (not tested for mutations, although I expect it to have the same issue):
`Service with \"MaybeConstructable<PostCrudResolver>\" identifier was not found in the container. Register it before usage via explicitly calling the \"Container.set\" function or using the \"@Service()\" decorator.`

Looks like it is the same problem that caused typestack/typedi#173, typestack/routing-controllers#642 and MichalLytek/type-graphql#775.

A current workaround is using TypeDI 0.8.0. Fixing by adding `@Service` to all classes will obviously break for projects not using TypeDI. Maybe an option that specified dependency injection could be passed to the generator?

**Comment by MichalLytek** [comment]
You can decorate your classes manually:

```ts
import { UserCrudResolver } from "@generate/type-graphql";
import { Service } from `type-di`;

Service(UserCrudResolver);
```

I can't generate resolvers with that decorator applied automatically.

**Comment by EirikFA** [comment]
There's proof of my lack of knowledge of decorators ¯\\\_(ツ)_/¯.

**Comment by MichalLytek** [comment]
@EirikFA This way of calling decorator is rather a hack. As the error says:
```
Register it before usage via explicitly calling the \"Container.set\" function or using the \"@Service()\" decorator."
```
you should be able to register the resolvers manually in container:
```ts
Container.set({ id: RecipeResolver, type: RecipeResolver });
```

**Comment by EirikFA** [comment]
Yep, I realised I could use `Container.set` after some trial and error (I was using `type` when I actually wanted `id`). :)

**Comment by MichalLytek** [comment]
Same, looks like the recent API changes were ill-considered and are unintuitive even for experienced users.

**Comment by TRANTANKHOA** [comment]
thanks all for the insights, just in case people want a snippet
```javascript
import {resolvers} from "@generated/type-graphql";
import {Service} from "typedi";

...

resolvers.forEach(
    (value, index, array) => array.forEach(v =>  {
        Service()(v); // https://github.com/MichalLytek/typegraphql-prisma/issues/63
    })
)
```
