### ISSUE TITLE
how to use generated args

### ISSUE THREAD

**Issue by cancng** [MichalLytek/typegraphql-prisma#66]
I want to use generated args for my resolver. For example we have admin only resolver and it lists all users. And we want to use `FindManyUserArgs` which includes cursor, distinct, orderBy etc...

I tried create new InputType class and extend `FindManyUserArgs` but couldn't do this.

**Comment by MichalLytek** [comment]
Github issues are not a helpdesk. Please ask your question in a proper place, like Gitter or Github Discussions:
https://github.com/MichalLytek/typegraphql-prisma/discussions
https://gitter.im/type-graphql/prisma2
