### ISSUE TITLE
Feature Request: Map filter fields(and possibly others) to different names(like "take" => "first")

### ISSUE THREAD

**Issue by omar-dulaimi** [MichalLytek/typegraphql-prisma#68]
Hello,

Since Prisma 1 api has slightly changed (like "first" was changed to "take"), It would be great if we could configure the generator to map the prisma fields(pagination for example) to other names.

# Why this is useful?

I believe many apps use the same conventions for GraphQL, say when paginating, the client sends a query with args like "first" set a number denoting that it should select a number of records to be returned. Now since Prisma introduced breaking API changes, web apps can easily avoid this issue since they're immediately updated at each deployment. But that is not the case for mobile apps since it's required that all users upgrade to the latest version, which doesn't really happen quickly in reality.

So ideally, we should be able to either use the current convention of TypeGraphQL to rename:

```
  /// @TypeGraphQL.take(name: "first")
```
Or globally through the generator config(if Prisma allows that):
```
generator typegraphql {
  provider = "typegraphql-prisma"
  output   = "../prisma/generated/type-graphql"
  customMap = {
    take: "first"
 }
}
```

Or any other possible ways

**Comment by MichalLytek** [comment]
`typegraphql-prisma` is a 1:1 mapper over a Prisma Client, that's why the names of the inputs and name of fields/arguments match them. Ability to rename `take` to `limit` or something like that is nice to have with a really low priority.

> I believe many apps use the same conventions for GraphQL, say when paginating, the client sends a query with args like "first" set a number denoting that it should select a number of records to be returned. 

I think you're talking about #18 which is a completely different pagination system 🤔

**Comment by omar-dulaimi** [comment]
In the meantime we're sticking to prisma's system since we accepted the breaking change.
