### ISSUE TITLE
Special characters in @@unique attribute result in invalid js files

### ISSUE THREAD

**Issue by jakeblaxon** [MichalLytek/typegraphql-prisma#77]
I have a schema that includes the following model:
```
model note {
  note_id   Int    @id
  order_id  Int
  note_type Int
  note      String

  @@unique([order_id, note_type], name: "UK.note.order_id.note_type")
}
```
Running `prisma generate` will succeed but my server will fail to start when I load the resolvers, giving me the following error: `ReferenceError: note is not defined`. I believe it's the periods in the `@@unique` attribute that's causing this error. When I use a string without periods, it loads fine. 

Here's a minimal reproduction: https://github.com/jakeblaxon/typegraphql-prisma-minimal-reproduction

Please let me know if you have any questions. Thanks!

**Comment by MichalLytek** [comment]
@jakeblaxon Does it also happens if you remove the `typegraphql-prisma` generator and leave only the Prisma Client one?

**Comment by jakeblaxon** [comment]
I don't believe so. I tried using just the prisma client and it seems to work ok. The error is specifically coming from `node_modules/@generated/type-graphql/resolvers/inputs/noteUK.note.order_id.note_typeCompoundUniqueInput.js:38`, so it appears that this file isn't getting generated correctly. My guess is that it has something to do with the periods in the name getting interpreted as separators in js, whereas it's supposed to be just one variable name based on the string.

**Comment by MichalLytek** [comment]
Blocked by DMMF issue: https://github.com/prisma/prisma/issues/6150

**Comment by MichalLytek** [comment]
Looks like we need to wait for Prisma fixing this issue: https://github.com/prisma/prisma/issues/3193

**Comment by do4gr** [comment]
A fix for this is now available when using the `namedConstraints` preview flag since 2.29.  See https://www.prisma.io/docs/guides/upgrade-guides/upgrading-to-use-preview-features/enabling-named-constraints

**Comment by MichalLytek** [comment]
Closing as `v0.14.8` now supports Prisma 2.29 🔒
