### ISSUE TITLE
typegraphql-prisma is ahead of latest stable prisma release

### ISSUE THREAD

**Issue by AviBueno** [MichalLytek/typegraphql-prisma#8]
Official prisma release is currently `2.8.1`, yet typegraphql-prisma requires `2.9.0-dev.36`
Could typegraphql-prisma separate between stable releases and dev releases?

**Comment by MichalLytek** [comment]
> Could typegraphql-prisma separate between stable releases and dev releases?

No, there's no time budget for separate releases. If there's a bug with stable release, I always upgrade to the latest dev one. If you can't use dev release, wait for another release with newer stable.

**Comment by MichalLytek** [comment]
Support for release 2.8.1 has been added in 8d92288.

Please watch the repo releases to be notified about publishing the patch release containing the fix.
