### ISSUE TITLE
Filtering Arrays by Contains

### ISSUE THREAD

**Issue by tradical-allstripes** [MichalLytek/typegraphql-prisma#84]
**Is your feature request related to a problem? Please describe.**
We often find ourselves in a situation where we want to filter our query results by whether an array/list column contains a particular value, which does not seem to be possible using the `FindMany` resolvers generated by `typegraphql-prisma`.

**Describe the solution you'd like**
 I looked into the generated code and the `StringNullableListFilter` only has an `equals` operation. I would recommend something like a `has` or `contains` operation. It would make a nontrivial increase in the utility of `typegraphql-prisma` for our use case.

**Describe alternatives you've considered**
*  Doing the filtering on the side consuming the API. This could become problematic as the data size grows
* Write custom resolvers. This is probably what I'll end up doing, but it's not quite as clean.

**Additional context**
In the meantime, if you know of a workaround, could you post it here for all to see?

**Comment by MichalLytek** [comment]
Please show your Prisma Schema - I never seen `StringNullableListFilter` 😕 

> I looked into the generated code and the StringNullableListFilter only has an equals operation. 

Can you look into a generated schema? `contains` is available just like in Prisma Client:

![image](https://user-images.githubusercontent.com/10618781/112721113-76c10580-8f02-11eb-96bf-d59e49fcebe0.png)

**Comment by MichalLytek** [comment]
I think you use Postgres arrays, like:
```prisma
model User {
  names String[]
}
```
Which generates `StringNullableListFilter`
```ts
@TypeGraphQL.InputType({
  isAbstract: true
})
export class StringNullableListFilter {
  @TypeGraphQL.Field(_type => [String], {
    nullable: true
  })
  equals?: string[] | undefined;

  @TypeGraphQL.Field(_type => String, {
    nullable: true
  })
  has?: string | undefined;

  @TypeGraphQL.Field(_type => [String], {
    nullable: true
  })
  hasEvery?: string[] | undefined;

  @TypeGraphQL.Field(_type => [String], {
    nullable: true
  })
  hasSome?: string[] | undefined;

  @TypeGraphQL.Field(_type => Boolean, {
    nullable: true
  })
  isEmpty?: boolean | undefined;
}
```

`typegraphql-prisma` is a 1:1 mapper for Prisma Client API, so please create your feature request on their repo: https://github.com/prisma/prisma

**Comment by tradical-allstripes** [comment]
Hey! Sorry I missed your reply a while ago...the notification got lost in the flood. I dunno how I missed then...I must have looked at the wrong generated code when we were switching from another tool to TGQL. I looked at it again and, sure enough, it is just as you say; 1:1 mapping to the Prisma Client; and it does have the feature I want. I apologize for the needless ticket...I know I've been taking up a non-trivial amount of your time lately. Your responsiveness is appreciated to a degree that was a notable selling point on this project for my team.
