### ISSUE TITLE
Wrong Prisma version in documentation

### ISSUE THREAD

**Issue by iamkacperwasik** [MichalLytek/typegraphql-prisma#93]
**Describe the issue**

Documentation says:
> Please make sure you use prisma and @prisma/client of version matching ~2.18.0. Otherwise, the runtime check will report an error when you run the generator.

But it throws:
> Error: Looks like you use an incorrect version of the Prisma packages: "2.18.0". Please ensure that you have installed a version that meets 'typegraphql-prisma' requirement: "~2.19.0".

**Comment by MichalLytek** [comment]
Fixed by 76818e6 🔒
